mission_security_footage_text = "TranslationHere",--Locate the hacked computer and use it to erase the Security Footage!
mission_apply_drill_text = "TranslationHere",--Mount the drill on the gate outside the vault area.
des_extra_cable_tie = "TranslationHere",--Extra cable ties gives more cable ties to start with. How much more depends on the upgrade level.
location_floor3 = "TranslationHere",--On Floor 3.
mission_thermite_wait = "TranslationHere",--Melt the floor (above the Vault)
mission_diamond_codes_hl = "TranslationHere",--Enter the codes.
location_str_1st = "TranslationHere",--On Scarlet St.
location_slaughterhouse_sewer_entry = "TranslationHere",--in the Sewer Entry.
mission_diamond_timelock_hl = "TranslationHere",--Wait for the time lock.
mission_slaughterhouse_prepare_ambush = "TranslationHere",--Get in position!
mission_hospital_cameras = "TranslationHere",--Take out all the cameras in and around the reception area.
intro_hospital122 = "TranslationHere",--WOLF: Yeah yeah yeah. Run the plan!
mission_undercover_interogation_hl = "TranslationHere",--CODES NOW!
intro_hospital134 = "TranslationHere",--STRANGER: Hooold the door!
mission_boat_drill_bridge = "TranslationHere",--Gain access to the bridge by blowing the bridge door open.
location_upper = "TranslationHere",--In Upper Hallways.
mission_suburbia_mission3_hl = "TranslationHere",--IT'S A TRAP!
intro_bridge = "TranslationHere",--10:45 pm, Green Bridge - southbound
intro_hospital137 = "TranslationHere",--Finally - two gentlemen in a building filled with clowns...
mission_bridge_locate_convoy = "TranslationHere",--Make your way further along the bridge and locate the prison convoy.
intro_hospital03 = "TranslationHere",--BAIN: Right...
location_dh_server = "TranslationHere",--In Server Room.
mission_undercover_escape2_hl = "TranslationHere",--ESCAPE!
tip_select_reward = "TranslationHere",--On the info screen you can choose amongst several skill-trees which lets you specialize in different areas. $NL; $NL; The trees give different perks and weapons, and you can have them all if your reputation is high enough.
location_dh_sales = "TranslationHere",--In Sales Department.
intro_bank02 = "TranslationHere",--We got a go from our insider... 
location_str_1ave = "TranslationHere",--On Foreign Ave.
mission_hospital_cooler = "TranslationHere",--Put two validated samples into the cooler.
location_dh_floor23 = "TranslationHere",--On Floor 23.
tip_trading_hostage = "TranslationHere",--A robber who loses all his health is put in custody. When in custody, you can only be brought back through a hostage trade. $NL; $NL; The police will contact Bain to set up the trade.
intro_secret_stash03 = "TranslationHere",--He's selling them a server with vital data. We screw 'em over, and snatch both Taxman and the server.
location_hospital_ExamG64 = "TranslationHere",--Examination G27
location_slaughterhouse_mainroom = "TranslationHere",--In the Main Room.
location_basement = "TranslationHere",--In Basement.
mission_undercover_saw_limo_hl = "TranslationHere",--SAW OPEN THE LIMO.
mission_apartment_detach2 = "TranslationHere",--Hold the fort and keep an eye on the saws.
location_ap_secretroom = "TranslationHere",--Room 145.
mission_suburbia_mission3_sub_2 = "TranslationHere",--Charge defused.
mission_slaughterhouse_load_gold = "TranslationHere",--Use the crane to lift the container containing the gold onto the truck.
intro_hospital147 = "TranslationHere",--WOLF: Man, this guy just can't stop talking!
intro_apartment04 = "TranslationHere",--and we're gonna take it all!
extra_cable_tie = "TranslationHere",--This upgrade adds extra cable ties.$NL;Need a lot of hostages to trade? This is it.
location_dh_bigred = "TranslationHere",--At Big Red.
intro_hospital01 = "TranslationHere",--BAIN: You're breaking up - can you hear me OK?
location_embassy = "TranslationHere",--At the Embassy.
mission_hospital_waitElevator = "TranslationHere",--Wait for the elevator to arrive while making sure to keep the power running.
intro_hospital20 = "TranslationHere",--WOLF: Guys... it feels like something's in the air... money!
mission_hospital_getToPatient = "TranslationHere",--Using the saw, open up the security door that holds the contaminated patient.
intro_hospital85 = "TranslationHere",--STRANGER: Why in the hell are you all dressed up?
mission_undercover_fasten_hl = "TranslationHere",--GET THE SERVER, PLUG IT IN.
des_hk21 = "TranslationHere",--STATS : 7.62mm : High capacity magazine$NL;Even though it was originally designed as a mounted machinegun, the Brenner 21 is a mobile powerhouse. With its huge capacity magazine, this is a given choice for the assault specialist.
des_trip_mine = "TranslationHere",--The trip mine consists of a beam projector affixed to a shaped explosive casing. The laser activates once the trip mine is placed, acting as a tripwire to detonate the mine. If the beam is broken or the charge fired upon, the mine will detonate.
intro_secret_stash07 = "TranslationHere",--Ready now!
des_beretta92 = "TranslationHere",--STATS : 9mm : Semiautomatic : Low recoil$NL;The B9-S is one of the most used law-enforcement pistols today.$NL;The relatively light damage is compensated by its big clips.$NL;A sidearm for the professional.
intro_hospital124 = "TranslationHere",--STRANGER: Hooold the door!
mission_undercover_check_hl = "TranslationHere",--CHECK THE LIMO.
intro_hospital127 = "TranslationHere",--...and may I say you two are the finest dressed nurses in the whole hospital!
intro_hospital92 = "TranslationHere",--WOLF: Yeah yeah yeah. Run the plan!
intro_hospital70 = "TranslationHere",--WOLF: Guys... it feels like something's in the air... money!
mission_apartment_winch = "TranslationHere",--Attach the magnet hanging from the helicopter to the top of the panic room.
intro_secret_stash01 = "TranslationHere",--The limo has arrived - Taxman is here.
mission_suburbia_mission5_hl = "TranslationHere",--GET THE WATER RUNNING.
location_str_x2st2ave = "TranslationHere",--By Major and Easy.
intro_hospital36 = "TranslationHere",--Should we... Can I take him out?
location_slaughterhouse_staffkitchen = "TranslationHere",--In the Staff Kitchen.
location_drill_office = "TranslationHere",--In Drill Area.
tip_tips = "TranslationHere",--TIPS:
location_dh_roofacces = "TranslationHere",--At Roof Access.
intro_street = "TranslationHere",--11:00 am, uptown - Double crossed
intro_hospital77 = "TranslationHere",--Is it Halloween!?
mission_undercover_crane_hl = "TranslationHere",--LIMO LIFT.
mission_boat_escape = "TranslationHere",--Escape!.
mission_slaughterhouse_load_gas = "TranslationHere",--Use the crane to lift the container with the trap in place.
location_suburbia_w_by = "TranslationHere",--At Wilson's Back
intro_hospital62 = "TranslationHere",--WOLF: Yeah yeah yeah. Run the plan!
mission_suburbia_mission3_sub_6 = "TranslationHere",--Charge defused.
intro_apartment01 = "TranslationHere",--Let's slip into our roles in this little drug deal charade...
location_uc_stair1 = "TranslationHere",--At Left Staircase
intro_hospital113 = "TranslationHere",--BAIN: Right...
intro_street02_2 = "TranslationHere",--There, Slick - now I call the shots!
mission_apartment_wait2 = "TranslationHere",--Hold the fort until the helicopter returns to lift the panic room.
mission_slaughterhouse_escape = "TranslationHere",--Make the escape through the container tunnel and spring the trap.
mission_bridge_identify = "TranslationHere",--Send up the Balloon so George can fly in and pick up the Ejection Seat.
location_dh_terrace = "TranslationHere",--On Terrace.
mission_hospital_callelevator_hl = "TranslationHere",--CALL THE ELEVATOR.
intro_hospital35 = "TranslationHere",--WOLF: Bain, we got a civilian too close...
mission_hospital_atrapp_hl = "TranslationHere",--SET UP FAKE SENTRY GUNS.
location_overpass = "TranslationHere",--On Overpass.
location_slaughterhouse_alley = "TranslationHere",--In the Alley.
location_slaughterhouse_loadingroom = "TranslationHere",--In the Loading Room.
intro_street01 = "TranslationHere",--OK, I'll take the plates - you erase the security footage.
intro_hospital42 = "TranslationHere",--WOLF: Yeah yeah yeah. Run the plan!
intro_hospital37 = "TranslationHere",--STRANGER: Aw Christ, look at ya.
location_dh_fitness = "TranslationHere",--In Fitness Center.
location_slaughterhouse_rooftop_stairs = "TranslationHere",--On the Rooftop Stairs.
mission_suburbia_mission10 = "TranslationHere",--See to it that the drill finishes it's job. The cops might try to turn the power off.
intro_suburbia = "TranslationHere",--12:00 pm, Suburbs - Bodhi's Pool Repair
mission_apartment_c42 = "TranslationHere",--Move downstairs, away from the C4!
location_cafeteria = "TranslationHere",--In Cafeteria.
mission_slaughterhouse_take = "TranslationHere",--Take the gold from the safe and load it into bags.
location_conferance = "TranslationHere",--In Conference Room.
location_suburbia_w_grage = "TranslationHere",--In Wilson's Garage
location_hospital_ReceptionCorridor = "TranslationHere",--Reception Corridor
mission_suburbia_mission1_hl = "TranslationHere",--TALK TO THE OWNER.
mission_get_drill = "TranslationHere",--Get the drill & thermite (Server Room.)
mission_bridge_jump_hl = "TranslationHere",--Make the escape (Bridge pillar.)
location_suburbia_m_by = "TranslationHere",--At Mitchell's Back
intro_hospital99 = "TranslationHere",--Problem is, Mr Alzheimers over here kept talking all the fucking time!
mission_apartment_panic = "TranslationHere",--Use the key to open the red door.
mission_suburbia_mission5 = "TranslationHere",--Go up to the tap and make sure the water is flowing.
des_mossberg = "TranslationHere",--STATS : 12 Gauge : Quick action$NL;The Locomotive is a compact, extremely fast 12-gauge shotgun.$NL;Clearing an entire room in a few seconds is what this was made for.
intro_hospital12 = "TranslationHere",--WOLF: Yeah yeah yeah. Run the plan!
location_hospital_ExamA13 = "TranslationHere",--Examination A13
mission_trough_lobby_text = "TranslationHere",--Get through the Lobby and make your way to the hallway outside the server room.
location_outside = "TranslationHere",--Outside.
reload_speed_multiplier = "TranslationHere",--This upgrade decreases the reload times of the weapon.$NL;Good for those intense moments.
location_uc_stairacces1 = "TranslationHere",--At Roof access left
location_dh_elevators23 = "TranslationHere",--By Elevators Floor 23.
intro_hospital75 = "TranslationHere",--WOLF (in Swedish): Finns det hjärterum, finns det stjärterum...
location_floor5 = "TranslationHere",--On Floor 5.
mission_suburbia_mission6_hl = "TranslationHere",--TAKE THE PLATES AND GET OUT!
mission_undercover_transaction = "TranslationHere",--Using BAIN's brain, Taxman's insider knowledge and the team's charms - get the IRS data base hacked for a huge tax cut.
mission_suburbia_mission11 = "TranslationHere",--Connect the rest of the hose to the hole in the safe.
mission_suburbia_mission2_hl = "TranslationHere",--HACK THE CODE LOCKS.
mission_apartment_key = "TranslationHere",--Locate Chavez - he is on one of the upper floors in the building, wearing a red beanie hat. Take the key from him.
intro_secret_stash06 = "TranslationHere",--Ok guys, at the right moment disrupt the deal, then Alex lifts the limo out of there.
des_mac11 = "TranslationHere",--STATS : .45 Caliber : Very high fire rate$NL;Against its original purpose, black market upgrades have converted the MARK11 into a fully automatic monster of a weapon.$NL;When in need of a close range bullet hose, look no further.
mission_thermite = "TranslationHere",--Pour out the thermite to melt the floor (above the vault).
intro_diamondheist02 = "TranslationHere",--Check!
mission_boat_aquire_drill = "TranslationHere",--Get the key from a staff-member and aquire the drill hidden in the bottom-deck cargo room.
location_suburbia_sewer = "TranslationHere",--In Sewers
location_str_x1st1ave = "TranslationHere",--By Foreign and Scarlet.
intro_hospital114 = "TranslationHere",--STRANGER: Hey! Hey - hold the goddamn door!
intro_hospital33 = "TranslationHere",--BAIN: Right...
tip_steelsight = "TranslationHere",--Aiming down your sights allows you to shoot more accurately than you do when you shoot from your hip.
des_m14 = "TranslationHere",--STATS : 7.62mm : Semiautomatic : Medium recoil$NL;Chambered for the 7.62 mm round, the M308 has made its way out on the black market after years of military service.$NL;When one well placed shot is all you need, this is it.
location_hospital_ExamH88 = "TranslationHere",--Examination H88
location_bridge_end = "TranslationHere",--At Bridge Pillar.
mission_boat_money_hl = "TranslationHere",--Collect the money.
des_ammo_bag = "TranslationHere",--The ammo bag is deployable equipment. Once placed it can be interacted with by any player to fully restore all ammo until depleted.
tip_melee_attack = "TranslationHere",--A hit with the butt of your weapon can be a good way to finish off an opponent. $NL; $NL; This is especially useful if you are low on ammo.
mission_suburbia_mission13 = "TranslationHere",--DEFUSE OR DIE!
mission_boat_saw_hl = "TranslationHere",--Saw down the obelisk.
mission_bridge_get_hostage_hl = "TranslationHere",--Find the Chinese prisoner (Convoy.)
mission_undercover_transaction_hl = "TranslationHere",--IRS HACK.
tip_mask_off = "TranslationHere",--Law enforcers won't take notice of you if your mask is off - use that to your advantage. $NL; $NL; Scout the place and take positions before you put your masks on. Once you have put your mask on, it can't be taken off for the remainder of the heist.
mission_suburbia_mission3 = "TranslationHere",--Defuse or DIE!
mission_get_into_vault_text = "TranslationHere",--Keep an eye on the drill - it jams.
des_thick_skin = "TranslationHere",--Thick Skin allows the wearer to receive more damage before going into bleed out. How much more depends on the upgrade level.
intro_hospital91 = "TranslationHere",--BAIN: You're breaking up - can you hear me OK?
mission_undercover_saw_limo = "TranslationHere",--Get Taxman out of the Limo! Saw open the roof and get him out!
mission_slaughterhouse_hide_hl = "TranslationHere",--Hide the Gold.
mission_callelevator_pickup = "TranslationHere",--Call the elevator and wait for it to arrive, then use it to make the escape from the roof.
mission_suburbia_mission4_hose = "TranslationHere",--Drag the water hose.
mission_apartment_key_hl = "TranslationHere",--Find Chavez and get his key.
mission_apartment_winch_hl = "TranslationHere",--Attach the magnet (Floor 4.)
mission_boat_stir_hl = "TranslationHere",--Stir the boat away from land.
location_hospital_ISOa = "TranslationHere",--Isolation A
mission_security_footage = "TranslationHere",--Erase the Security Footage (Management.)
location_slaughterhouse_sewer_exit = "TranslationHere",--In Sewer Exit.
location_office = "TranslationHere",--In Second Office Building.
intro_slaughterhouse01 = "TranslationHere",--...and also on the 45 goin' south, there's been a major accident that's clogging the entire freeway...
mission_diamond_escape = "TranslationHere",--Make your way to the helicopter. It can't stay in the same place for too long!
mission_apartment_roof_hl = "TranslationHere",--Secure the roof (Roof.)
mission_slaughterhouse_take_hl = "TranslationHere",--Take the gold!
mission_apartment_escape_hl = "TranslationHere",--Escape (Basement.)
intro_hospital04 = "TranslationHere",--Go to the fourth floor - the infection clinic.
location_dh_construction = "TranslationHere",--At Construction.
intro_hospital47 = "TranslationHere",--Aw, hell...
intro_hospital46 = "TranslationHere",--*cough* *cough* *cough* *cough*
damage_multiplier = "TranslationHere",--This upgrade increases the damage of the weapon.$NL;Nice when taking down heavier enemies.
intro_hospital148 = "TranslationHere",--I'll kill him first!
mission_hospital_ICU_hl = "TranslationHere",--SAW OPEN THE DOORS INTO THE ICU.
mission_slaughterhouse_prepare_gas_hl = "TranslationHere",--Prepare a trap!
location_hospital_ExamD45 = "TranslationHere",--Examination D45
mission_undercover_fasten = "TranslationHere",--Get the server from the Limo and make your way to the transfer room to plug it in.
mission_suburbia_mission10_hl = "TranslationHere",--LET THE DRILL FINISH.
location_slaughterhouse_safehouse = "TranslationHere",--In the Safe House.
mission_boat_get_key = "TranslationHere",--Get the key from a securityguard and gain access to the securityroom.
mission_slaughterhouse_drill = "TranslationHere",--Drill open the safe.
mission_sec_doors_hl = "TranslationHere",--Plant tablets on the remaining alarm boxes.
intro_bank03 = "TranslationHere",--he hid the thermite and a drill in the server room - but he bailed.
location_str_2st = "TranslationHere",--On Easy St.
location_dh_pr = "TranslationHere",--In PR Department.
mission_undercover_check = "TranslationHere",--Check the Limo and see if you can get the Taxman out of it.
location_slaughterhouse_mainroom_walkway = "TranslationHere",--On the Main Room Walkway.
mission_boat_money = "TranslationHere",--Collect the money into bags.
location_hospital_ICUArea = "TranslationHere",--ICU Area
thick_skin = "TranslationHere",--This upgrade gives extra health.$NL;Being a criminal toughens your skin.
trip_mine_damage = "TranslationHere",--This upgrade increases the explosive power and blast radius of your trip mines.
mission_get_drill_text = "TranslationHere",--Get the drill and the thermite.
location_dh_security = "TranslationHere",--In Security Room.
location_vault_above = "TranslationHere",--Above Vault.
intro_suburbia01 = "TranslationHere",--Bodhi's Pool Repair.
tip_dont_shoot_civilians = "TranslationHere",--Don't shoot civilians. For each civilian you kill, penalty time is added to your regular custody time. $NL; $NL; This means that if you are put in custody, you will have to wait longer before the police make an offer to trade you for a hostage.
location_hospital_BreakRoom = "TranslationHere",--Break Room
location_hospital_Office = "TranslationHere",--Office
mission_diamond_loot_hl = "TranslationHere",--Steal the diamonds.
mission_apartment_wait_hl = "TranslationHere",--Wait for the explosives (Roof.)
location_dh_roof = "TranslationHere",--On Roof.
mission_get_into_vault = "TranslationHere",--Drill the gates (Drill Area.)
tip_secret_assignmnet = "TranslationHere",--The four types of special units are very dangerous, especially if you face them alone. $NL; $NL; Team up to take them down!
mission_suburbia_mission3_sub_5 = "TranslationHere",--Charge defused.
mission_hospital_cameras_hl = "TranslationHere",--TAKE OUT THE CAMERAS.
location_bridge_convoy = "TranslationHere",--At Convoy.
mission_diamond_escort2_hl = "TranslationHere",--Get Mr. Garnet's son Ralph.
des_toolset = "TranslationHere",--The toolkit allows the owner to organize, carry and protect the tools, making them more effective. How much more depends on the upgrade level.
tip_shoot_in_bleed_out = "TranslationHere",--While in bleed-out, you can still fire your sidearm. $NL; $NL; When a partner is helping you up you can protect the both of you, but provoking law enforcers while on your own makes you an easy and helpless target.
mission_hospital_disguise_hl = "TranslationHere",--PLAY DOCTOR.
des_m79 = "TranslationHere",--STATS : 40mm rounds : Single-shot : Break Action$NL;"The Thump-Gun", "The Skill Cannon", "The Pro Pipe", "The Noob Tube", and "The Ex-Wife" - things we love have many names. The GL40 is a single-shot, shoulder-fired break action grenade launcher that aims to please.
mission_hospital_drawblood = "TranslationHere",--Draw blood from the patient, and use the validation machines around the hospital to validate the blood sample. Don´t spill it!
location_suburbia_str24 = "TranslationHere",--At Keel and Spinnaker
location_hospital_northCorridor = "TranslationHere",--North Corridor
mission_diamond_loot = "TranslationHere",--Enter the vault and steal the diamonds.
intro_hospital56 = "TranslationHere",--Let's get going, OK? *cough* *cough*
intro_bank = "TranslationHere",--2:15 pm, downtown - First World Bank
intro_hospital39 = "TranslationHere",--WOLF: I didn't quite catch that... But let's go.
mission_slaughterhouse_drill_hl = "TranslationHere",--Drill the safe
intro_street01_2 = "TranslationHere",--Come on we got it, let's get out of here!
mission_diamond_wait = "TranslationHere",--Wait while Bain is negotiating for the codes.
intro_hospital115 = "TranslationHere",--You think just because you're wearing $5.000 suits you don't need to hold the door?!
mission_get_key_text = "TranslationHere",--Find the bank manager - Look for a yellow outline once he's identified.
mission_diamond_timelock = "TranslationHere",--Wait for the time lock to expire.
location_str_drakes = "TranslationHere",--At Drake's Loading.
mission_blow_wall = "TranslationHere",--Blow a hole in the wall (Management.)
trip_mine_quantity = "TranslationHere",--This upgrade adds extra trip mines to the inventory.$NL;A couple of extra mines will increase your chances.
fire_rate_multiplier = "TranslationHere",--This upgrade increases the rate of fire.$NL;Eats through enemies like it eats through ammunition.
location_hospital_ElevatorShaft = "TranslationHere",--Elevator Shaft
location_roof = "TranslationHere",--On Roof.
intro_hospital107 = "TranslationHere",--That's just bad for business!
mission_apartment_c42_hl = "TranslationHere",--Move away from the C4 (Floor 2.)
mission_boat_aquire_drill_hl = "TranslationHere",--Get the Drill
mission_thermite_wait_text = "TranslationHere",--Hold the fort and let the thermite burn through the floor. There are two cans of thermite hidden in the copy machine, if both are carried to the vault it will speed up the melting process.
mission_suburbia_mission8_hl = "TranslationHere",--MAKE SURE THE WATER'S FLOWING.
mission_suburbia_mission4_drill = "TranslationHere",--Apply the drill to the safe.
explosion_range_multiplier = "TranslationHere",--This upgrades the explosion range for the GL40 Grenade Launcher.$NL;The only thing better than an explosion - is a bigger explosion.
mission_suburbia_mission4_info = "TranslationHere",--Hose stretch completed
des_r870_shotgun = "TranslationHere",--STATS : 12 Gauge : Very high damage$NL;There is no more powerful firearm than the pump-action, 12 gauge bore Reinbeck shotgun.$NL;What it lacks in speed, it makes up for in raw, indisputable power.
location_slaughterhouse_alley_stairs = "TranslationHere",--On the Alley Stairs.
mission_apartment_bag = "TranslationHere",--Alex dropped off the C4 bag, find it.
location_hospital_ExamA12 = "TranslationHere",--Examination A12
intro_hospital50 = "TranslationHere",--WOLF: Guys... it feels like something's in the air... money!
mission_hospital_hostage = "TranslationHere",--Keep the civilians from activating the alarm until Bain is finished scanning the database.
location_hospital_Exam22 = "TranslationHere",--Examination B22
intro_hospital27 = "TranslationHere",--What are you monkies dressed up for - a wedding or a f...
intro_hospital143 = "TranslationHere",--BAIN: Right...
toolset = "TranslationHere",--This upgrade makes you interact faster.$NL; When you need to get in and out fast as hell, the Toolkit might be something for you.
ammo_bag = "TranslationHere",--The ammo bag can be deployed on the ground, so that you and your crew can use it.$NL;Ammo for everyone.
location_dh_heliroof = "TranslationHere",--On Roof Helipad.
location_slaughterhouse_walkway = "TranslationHere",--On the Walkway.
mission_undercover_interogation = "TranslationHere",--Get the codes from Taxman! Screams, threats and a good old beating - anything goes - we are in a hurry!
location_hospital_construction = "TranslationHere",--Construction
mission_boat_destroy_security_equipment_hl = "TranslationHere",--Destroy equipment.
location_str_parking = "TranslationHere",--At Jake's Parking.
mission_slaughterhouse_smoke = "TranslationHere",--Block the helicopters view with smoke from a burning tire pile!
intro_hospital55 = "TranslationHere",--Come on! Unless you two plan on operating on me here, you better make room!
mission_apartment_wait2_hl = "TranslationHere",--Wait for the helicopter to return to the roof (Roof.)
mission_apartment_door_hl = "TranslationHere",--Locate the Panic Room (Floor 3.)
mission_undercover_power_hl = "TranslationHere",--KEEP THE POWER.
mission_slaughterhouse_load_gold_hl = "TranslationHere",--Lift the gold out of here!
intro_hospital73 = "TranslationHere",--BAIN: Right...
mission_apartment_wait = "TranslationHere",--Wait for the helicopter to drop the C4 on the roof.
mission_diamond_escort2 = "TranslationHere",--Find Mr. Garnet's son Ralph and take him to our chopper on the roof.
intro_secret_stash04 = "TranslationHere",--With those, we'll make a $25,000,000 hack. Alex, crane ready?
location_slaughterhouse_sewer = "TranslationHere",--In the Sewer.
intro_hospital109 = "TranslationHere",--WOLF: Bain, grampa over here kept talking so we didn't hear you. Fuck it, let's just improvise.
intro_street03_2 = "TranslationHere",--What the..! What are you doin' Matt!?
intro_diamondheist = "TranslationHere",--1:30 am, 22nd floor - Garnet Group Skyscraper
location_hospital_laundry = "TranslationHere",--Laundry room
intro_hospital21 = "TranslationHere",--BAIN: You're breaking up - can you hear me OK?
mission_boat_restart_engine = "TranslationHere",--Get down to the enginge room and get the enginge running again.
location_suburbia_str1 = "TranslationHere",--On Pacific Drv.
intro_hospital63 = "TranslationHere",--BAIN: Right...
mission_boat_stir = "TranslationHere",--Stir the boat away from land into international water.
location_suburbia_shelter = "TranslationHere",--In Shelter
intro_hospital97 = "TranslationHere",--*chuckle* What a racket...
intro_bridge04 = "TranslationHere",--Let's go, guys!
mission_apartment_bag_hl = "TranslationHere",--Locate the C4 Bag.
location_backalley = "TranslationHere",--In Back Alley.
location_cokeoverkill = "TranslationHere",--By the OVERKILL Cola sign.
intro_hospital52 = "TranslationHere",--WOLF: Yeah yeah yeah. Run the plan!
intro_slaughterhouse03 = "TranslationHere",--Looks like the diversion worked - they've changed their course. Convoy should be here in moments!
intro_hospital100 = "TranslationHere",--WOLF: Guys... it feels like something's in the air... money!
intro_bank01 = "TranslationHere",--Alright guys, listen up - good news and bad news:
location_uc_floor1 = "TranslationHere",--On Floor 1
mission_diamond_sneak_hl = "TranslationHere",--Sneak and access the alarm boxes.
mission_suburbia_mission4 = "TranslationHere",--Apply the drill to the safe and plug the power cord into an outlet. As soon as the drill is done, drag the water hose down to the basement and connect it.
location_slaughterhouse_main_corridor = "TranslationHere",--In the Main Corridor.
des_m4 = "TranslationHere",--STATS : 5.56mm : Semiautomatic : Medium recoil$NL;The AMCAR-4 is one of the most versatile assault rifles there is.$NL;The good accuracy coupled with the high rate of fire prepares its owner for any situation.
tip_weapon_effecienty = "TranslationHere",--Different weapons are more effective at different ranges, and are therefore suited for different situations.
location_hospital_Elevator = "TranslationHere",--Elevator
intro_hospital31 = "TranslationHere",--BAIN: You're breaking up - can you hear me OK?
mission_diamond_sneak = "TranslationHere",--Sneak around and gain access to the consoles controlling the vault doors. If the alarm goes off, Bain will have to hack the remaining consoles.
location_hospital_ExamF64 = "TranslationHere",--Examination F64
intro_hospital61 = "TranslationHere",--BAIN: You're breaking up - can you hear me OK?
location_dh_managment = "TranslationHere",--In Management.
location_bridge_boat = "TranslationHere",--On A Boat.
intro_hospital103 = "TranslationHere",--BAIN: Right...
intro_hospital138 = "TranslationHere",--I can tell you're good people.
intro_hospital81 = "TranslationHere",--BAIN: You're breaking up - can you hear me OK?
mission_slaughterhouse_gasoline_hl = "TranslationHere",--Get the Gasoline!
intro_hospital83 = "TranslationHere",--BAIN: Right...
tip_shoot_at_civilians = "TranslationHere",--Shout at civilians to keep them in check. $NL; $NL; A living civilian is always an asset, and lying down he/she is more likely to stay alive.
intro_hospital88 = "TranslationHere",--"blah blah blah pick you up from the roof when we're done."
intro_hospital145 = "TranslationHere",--Aw, Christ in a handbag - are you two cops?
mission_slaughterhouse_attack_convoy_hl = "TranslationHere",--Hit the convoy!
intro_diamondheist03 = "TranslationHere",--Remember: Stay low, stay dark, avoid guards and gunfire. Here we go...
mission_bridge_get_hostage = "TranslationHere",--Locate the prisoner! He's in one of the trucks. Saw the doors open.
mission_suburbia_mission4_power = "TranslationHere",--Hook up the drill to an outlet.
location_vault_hallway = "TranslationHere",--In Vault Hallway.
mission_diamond_escape_hl = "TranslationHere",--Escape!
location_suburbia_m_garage = "TranslationHere",--In Mitchell's Garage
intro_bridge01 = "TranslationHere",--OK, stay low everybody. I'm detonating in four, three, two, cover, ignition!
mission_diamond_escort1_hl = "TranslationHere",--Change of plan, get the CFO.
location_slaughterhouse_lockerroom = "TranslationHere",--In the Locker Room.
location_suburbia_str4 = "TranslationHere",--On Spinnaker Str.
tip_tactical_reload = "TranslationHere",--You can reload your weapon even if you haven't completely emptied your current ammo clip. $NL; $NL;This way you make sure that you have a full clip the next time you run into trouble. This is called a "tactical reload".
mission_bridge_escort_hl = "TranslationHere",--Escort the prisoner (Scaffolding.)
des_c45 = "TranslationHere",--STATS : .45 Caliber : Semiautomatic : Medium recoil$NL;The C45 is a very reliable weapon that has proven its worth over years of use. It does enough damage and carries enough rounds to handle most targets. A good all rounder.
mission_slaughterhouse_escape_hl = "TranslationHere",--Make the escape!
mission_slaughterhouse_load_gas_hl = "TranslationHere",--Set the trap in place!
intro_hospital53 = "TranslationHere",--BAIN: Right...
location_uc_floor2 = "TranslationHere",--On Floor 2
mission_hospital_atrapp = "TranslationHere",--Set up the fake sentry guns so that the civilians will stay down.
tip_switch_to_sidearm = "TranslationHere",--It is always quicker to switch to your sidearm than reloading your primary weapon. $NL; $NL; So if you run out of ammo for your SMG and you're in a tight spot, switching to your sidearm instead of reloading could save your life.
mission_suburbia_mission6 = "TranslationHere",--Take the printing plates from within the safe.
doctor_bag_increase = "TranslationHere",--This upgrades the amount of health that can be acquired from the bag.$NL;It will help you help your friends even more.
mission_hospital_rounds_hl = "TranslationHere",--FIND OUT WHERE THE CONTAMINATED PATIENT IS.
mission_get_into_bank_hl = "TranslationHere",--Enter the bank (Lobby.)
intro_hospital64 = "TranslationHere",--STRANGER: Let's go, let's go! We can all fit in the elevator!
intro_bank04 = "TranslationHere",--The bank manager's got the key card to get in there - let's get it on.
intro_slaughterhouse = "TranslationHere",--8:01 am, Slaughterhouse district - AMBUSH!
intro_slaughterhouse02 = "TranslationHere",--...it's like a war zone out there so this morning you better take scenic route!
ammo_bag_increase = "TranslationHere",--This upgrades the amount of ammo that can be acquired from the bag.$NL;Even more ammo for everyone.
mission_hospital_cooler_amount_text = "TranslationHere",--BLOOD SAMPLES IN COOLER.
intro_suburbia04 = "TranslationHere",--Yeah, you hurry!
mission_suburbia_escape = "TranslationHere",--Open the grate and enter the storm drains. Escape the storm drains and say hi to the pacific!
des_mp5 = "TranslationHere",--STATS : 9mm : High rate of fire and low recoil$NL;COMPACT-5 is hands down the most frequently used weapon of special operation units.$NL;With its low recoil and compact size it is ideal for urban combat.
location_hospital_ExamE52 = "TranslationHere",--Examination E52
mission_suburbia_mission2 = "TranslationHere",--Get access to the secret criminal enterprise under Mitchell's pool.
location_slaughterhouse_toilet = "TranslationHere",--In the Toilet.
tip_help_bleed_out = "TranslationHere",--If a robber is shot down he goes into "bleed-out", where he can't move and can only shoot with his sidearm. $NL; $NL; A robber in bleed-out can be helped back up at no cost.
intro_hospital11 = "TranslationHere",--BAIN: You're breaking up - can you hear me OK?
location_suburbia_str2 = "TranslationHere",--On Keel Str.
mission_ap_c4_sub_top = "TranslationHere",--Place the charges on the roof.
location_slaughterhouse_yard = "TranslationHere",--On the Yard.
location_str_x1st2ave = "TranslationHere",--By Scarlet and Major.
location_str_3ave = "TranslationHere",--On Armitage Ave.
location_dh_party = "TranslationHere",--At Party.
mission_bridge_heli_clear = "TranslationHere",--Hold the tower, wait for the airplane and make sure George snatches up the chair!
mission_hospital_ICU = "TranslationHere",--Use the hidden saw that looks like a teddybear, and start sawing your way through the ICU doors.
intro_hospital90 = "TranslationHere",--WOLF: Guys... it feels like something's in the air... money!
mission_undercover_crane = "TranslationHere",--While Alex is lifting the limo to the roof, make sure to Keep the FBI at bay.
intro_apartment = "TranslationHere",--4:02 pm, projects - Chavez's crib
mission_apartment_start_hl = "TranslationHere",--Drug deal (Lobby.)
mission_slaughterhouse_gasoline = "TranslationHere",--Find the cans of gasoline.
intro_hospital118 = "TranslationHere",--Fuck it, let's just improvise.
intro_hospital72 = "TranslationHere",--WOLF: Yeah yeah yeah. Run the plan!
location_uc_stairacces2 = "TranslationHere",--At Roof access right
intro_street04 = "TranslationHere",--What the..! What are you doing, Matt!?
intro_suburbia02 = "TranslationHere",--Bonjour, it's Mitchell over on Keel Street. The pipes, you know the ones you've supposedly fixed, they're leaking again.
intro_hospital89 = "TranslationHere",--Sounds like a plan.
location_floor2 = "TranslationHere",--On Floor 2.
mission_diamond_escort1 = "TranslationHere",--We need to pressure Mr. Garnet into giving us the access codes to the vault. Bain is trying to locate the CFO using security footage, but try to find him sooner than that.
mission_hospital_cooler_hl = "TranslationHere",--PUT TWO VALIDATED SAMPLES INTO THE COOLER.
mission_bridge_jump = "TranslationHere",--Make it to the Bridge Pillar and take the stairs to the waiting scuba gear.
intro_hospital129 = "TranslationHere",--I'll kill him first.
tip_xp_bar = "TranslationHere",--The cash gauge is in the lower left corner of the screen. $NL; $NL; It shows how much more cash you need to collect to reach your next level of reputation, and what weapon, equipment or ability you will be rewarded with.
des_more_ammo = "TranslationHere",--All your teammates get to carry more ammo. The benefit of a Crew Bonus only applies to the three teammates of the one who equips it. This means that someone else on the team needs to equip a crew bonus in order for you to directly benefit from it. Multipliers do not stack if several teammates equip the same crew bonus.
mission_suburbia_escape_hl = "TranslationHere",--ESCAPE!
des_glock = "TranslationHere",--STATS : 9mm : Full Auto : Low recoil$NL;The military has it, the police have it, and now you have it. The Stryk is an easy to use fully automatic pistol, specifically designed to fight crime. Wait a minute...
location_druglab = "TranslationHere",--In Drug Lab.
mission_hospital_rapport = "TranslationHere",--Look through the files and find the correct patient file.
mission_bridge_locate_convoy_hl = "TranslationHere",--Locate the prison convoy (Convoy.)
location_management = "TranslationHere",--In Management.
intro_hospital54 = "TranslationHere",--STRANGER: Back up, let me in! WOLF: Good day, sir...
location_suburbia_str23 = "TranslationHere",--At Keel and Marine
des_gang_of_ninjas = "TranslationHere",--All your teammates melee attack range increases. The benefit of a Crew Bonus only applies to the three teammates of the one who equips it. This means that someone else on the team needs to equip a crew bonus in order for you to directly benefit from it. Multipliers do not stack if several teammates equip the same crew bonus.
location_front = "TranslationHere",--In Front.
intro_hospital43 = "TranslationHere",--BAIN: Right...
intro_hospital105 = "TranslationHere",--Do either of you have a smoke?
intro_street03 = "TranslationHere",--There, Slick! Now I call the shots!
intro_hospital76 = "TranslationHere",--What in the hell are you two dressed up for...
intro_hospital26 = "TranslationHere",--STRANGER: Yeah... thanks, I guess.
intro_apartment02 = "TranslationHere",--those junkies won't know what hit 'em before it's too late.
intro_hospital128 = "TranslationHere",--WOLF: Aaargh, you old fart!
intro_hospital146 = "TranslationHere",--I was gonna light up... You ain't gonna arrest me, are ya?
clip_ammo_increase = "TranslationHere",--This upgrade adds more bullets to every clip.$NL;Some extra bullets can make all the difference in the world.
mission_undercover_deal = "TranslationHere",--Wait until the SERVER is exposed before you hit them! That server is the only way to make our transaction!
tip_doctor_bag = "TranslationHere",--The doctor's bag is a real life saver. $NL; $NL; If your team runs low on health, place your doctor's bag on the ground and let everyone patch themselves up!
des_extra_start_out_ammo = "TranslationHere",--Extra start out ammo allows the owner to carry more ammo. How much more depends on the upgrade level.
mission_apartment_intro = "TranslationHere",--Let Chavez buzz you in, and then enter the building through the back door.
mission_apartment_roof = "TranslationHere",--Rid the roof of all the law enforcers.
tip_police_free_hostage = "TranslationHere",--The police will always take the opportunity to free hostages when no robber is nearby. $NL; $NL; Spread your crew out and keep an eye on all the hostages - they are your life lines!
location_plaza = "TranslationHere",--On Plaza.
mission_bridge_identify_hl = "TranslationHere",--Send up the Balloon (Scaffolding.)
intro_hospital102 = "TranslationHere",--WOLF: Yeah yeah yeah. Run the plan!
mission_boat_destroy_security_equipment = "TranslationHere",--Destroy all security equipment in the securityroom.
location_floor4 = "TranslationHere",--On Floor 4.
mission_hospital_enterelevator_hl = "TranslationHere",--TAKE THE ELEVATOR TO THE ROOF.
mission_undercover_power = "TranslationHere",--See to it that the cops do not cut the power, if they do you have to turn it back on fast to keep the computers running.
mission_enterelevator_pickup = "TranslationHere",--Take the elevator to get to the exit on the roof.
des_aggressor = "TranslationHere",--All your teammates get a damage multiplier. The benefit of a Crew Bonus only applies to the three teammates of the one who equips it. This means that someone else on the team needs to equip a crew bonus in order for you to directly benefit from it. Multipliers do not stack if several teammates equip the same crew bonus.
mission_apartment_intro_hl = "TranslationHere",--Entrance (Back alley.)
location_str_crash = "TranslationHere",--At Inkwell Industrial.
intro_hospital17 = "TranslationHere",--I remember when you could smoke in the operating room! *chuckle*
location_firescape = "TranslationHere",--On Fire Escape.
spread_multiplier = "TranslationHere",--This upgrade increases the precision of the weapon.$NL;Good for long range shots.
mission_apartment_detach2_hl = "TranslationHere",--Keep the saws going (Floor 2 and 3.)
location_slaughterhouse_bosshouse = "TranslationHere",--In the Office.
mission_hospital_getToPatient_hl = "TranslationHere",--PICK THE RIGHT DOOR TO OPEN.
mission_hospital_hostage_hl = "TranslationHere",--KEEP THE HOSTAGES DOWN.
mission_apartment_roof2 = "TranslationHere",--Alex needs to wait for the smoke to clear, you need to keep the police off the roof until then.
des_sharpshooters = "TranslationHere",--All your teammates get improved accuracy. The benefit of a Crew Bonus only applies to the three teammates of the one who equips it. This means that someone else on the team needs to equip a crew bonus in order for you to directly benefit from it. Multipliers do not stack if several teammates equip the same crew bonus.
tip_help_arrested = "TranslationHere",--Try to complete challenges - these award cash and are a good way to progress fast. $NL; $NL; All the challenges and their objectives are listed in the main menu.
mission_apartment_detach = "TranslationHere",--Saw off the beams above and below the panic room to detach it from the floor.
intro_hospital86 = "TranslationHere",--You two in some... goddamn... boy band!?
mission_apply_drill = "TranslationHere",--Start the drill (Drill Area.)
intro_street05 = "TranslationHere",--Haha! Fooled ya guys!
sentry_gun_armor_increase = "TranslationHere",--This upgrades the amount of heat your sentry gun can take before going out.$NL;When you are in a tight spot, this might save your life.
trip_mine = "TranslationHere",--Trip mines can be placed anywhere and are triggered by a laser "trip line".$NL;Having issues watching your back or taking out special units? This could be it.
location_slaughterhouse_rooftop = "TranslationHere",--On the Rooftop.
intro_hospital144 = "TranslationHere",--STRANGER: Hold that door!
mission_hospital_cooler_sub1 = "TranslationHere",--First blood sample.
intro_hospital05 = "TranslationHere",--We're here to draw some blood from a guy that they have in quarantine.
mission_hospital_rounds = "TranslationHere",--Figure out a way to get to the contaminated patient. Prove your Harvard degree paid off.
location_bridge_scaffhold = "TranslationHere",--On Scaffolding.
intro_slaughterhouse04 = "TranslationHere",--OK, ready for action. These are Murky Water mercenaries, remember; use cover and shoot in short controlled bursts.
mission_bridge_gear_hl = "TranslationHere",--Get the gear!
tip_objectives = "TranslationHere",--Your current objective is shown in the upper left corner of the screen. $NL; $NL; A more detailed description of the objective, as well as a list of completed objectives, can be seen in the info screen.
mission_boat_get_key_hl = "TranslationHere",--Get the key.
mission_undercover_escort = "TranslationHere",--We need to get the Taxman to the transfer room we started out in. Use all necessary force to make him cooperate.
location_uc_floor3 = "TranslationHere",--On Floor 3
mission_suburbia_mission2_hack2 = "TranslationHere",--Override Wilson's code lock.
intro_suburbia03 = "TranslationHere",--Sorry to hear that, sir. We'll send our guys over right away.
mission_hospital_rapport_hl = "TranslationHere",--FIND THE CORRECT PATIENT FILE.
location_hospital_mainCorridor = "TranslationHere",--Main Corridor
intro_hospital13 = "TranslationHere",--BAIN: Right...
location_uc_roof = "TranslationHere",--On Roof
des_welcome_to_the_gang = "TranslationHere",--All your teammates get a cash multiplier. The benefit of a Crew Bonus only applies to the three teammates of the one who equips it. This means that someone else on the team has to equip a Crew Bonus in order for you to directly benefit from it. Multipliers do not stack if several teammates equip the same crew bonus.
mission_get_key = "TranslationHere",--Find the bank manager.
intro_hospital24 = "TranslationHere",--STRANGER: Back up! *cough* *cough*
intro_hospital60 = "TranslationHere",--WOLF: Guys... it feels like something's in the air... money!
location_suburbia_str14 = "TranslationHere",--At Pacific and Spinnaker
location_suburbia_w_fy = "TranslationHere",--At Wilson's Front
mission_thermite_text = "TranslationHere",--Pour out the thermite in the office above the vault - it will burn a hole through the steel floor. There are two cans of thermite hidden in the copy machine, if both are carried to the vault it will speed up the melting process.
location_uc_ground = "TranslationHere",--On Ground floor
mission_ap_c4_sub_mid = "TranslationHere",--Place the charges on floor 5.
location_floor1 = "TranslationHere",--On Floor 1.
mission_suburbia_mission13_hl = "TranslationHere",--IT'S A TRAP!
location_slaughterhouse_outside_entrance = "TranslationHere",--At the Slaughterhouse Entrance.
intro_hospital25 = "TranslationHere",--WOLF: Come on in.
mission_blow_wall_text = "TranslationHere",--Apply C4 to the wall next to the server room and blow a hole into the neighboring building.
location_dh_admin = "TranslationHere",--In Administration.
sentry_gun = "TranslationHere",--Based on internet blueprints, the Sentry Gun is a criminal's best friend. Two guns connected to a computer automatically aim and fire at any target detected by its sensors. Being the bad guy has never felt more alien.
des_speed_reloaders = "TranslationHere",--All your teammates reload faster. The benefit of a Crew Bonus only applies to the three teammates of the one who equips it. This means that someone else on the team needs to equip a crew bonus in order for you to directly benefit from it. Multipliers do not stack if several teammates equip the same crew bonus.
location_dh_floor22 = "TranslationHere",--On Floor 22.
location_slaughterhouse_container_area = "TranslationHere",--In the Container Area.
mission_sec_doors = "TranslationHere",--Some consoles are still online. Plant the tablets on and let Bain hack the alarm system.
intro_hospital106 = "TranslationHere",--Goddamn hospital removed their cigarette machines!
location_bridge_bridge = "TranslationHere",--On Bridge.
mission_suburbia_mission11_hl = "TranslationHere",--CONNECT THE HOSE TO THE SAFE.
mission_boat_drill_bridge_hl = "TranslationHere",--Blow the bridge door open
location_suburbia_str13 = "TranslationHere",--At Pacific and Marine
mission_undercover_shoot_limo_hl = "TranslationHere",--FREE THE LIMO.
location_balcony = "TranslationHere",--On Balcony.
intro_hospital38 = "TranslationHere",--How many insurance claims did you deny to get those suits?
mission_slaughterhouse_attack_convoy = "TranslationHere",--Attack and halt the convoy!
intro_hospital98 = "TranslationHere",--WOLF: Hey Bain, great briefing... ah...
intro_hospital32 = "TranslationHere",--WOLF: Yeah yeah yeah. Run the plan!
mission_empty_vault_text = "TranslationHere",--Empty the Vault! Get the Cash!
mission_diamond_codes = "TranslationHere",--Get to the vault doors and enter the codes to gain access to the vault.
location_hospital_roofelevator = "TranslationHere",--Roof Elevator
intro_slaughterhouse05 = "TranslationHere",--Let's get to work.
mission_trough_lobby = "TranslationHere",--Get through the Lobby.
intro_hospital28 = "TranslationHere",--Yeah, alright - I forgot where I was.
mission_bridge_heli_clear_hl = "TranslationHere",--Defend (Scaffolding.)
des_sentry_gun = "TranslationHere",--Based on internet blueprints, the Sentry Gun is a criminal's best friend. Two guns connected to a computer automatically aim and fire at any target detected by its sensors. Being the bad guy has never felt more alien.
mission_undercover_escort_hl = "TranslationHere",--TAKE TAXMAN TO TRANSFER ROOM.
des_mr_nice_guy = "TranslationHere",--All your teammates get a cash multiplier. The benefit of a Crew Bonus only applies to the three teammates of the one who equips it. This means that someone else on the team needs to equip a crew bonus in order for you to directly benefit from it. Multipliers do not stack if several teammates equip the same crew bonus.
location_hospital_serviceArea = "TranslationHere",--Service area
location_dh_atrium = "TranslationHere",--In Atrium.
mission_undercover_roof = "TranslationHere",--Wait for Taxman to show the server we are after. Scare him into his limo when you see it - we need both the server and the Taxman. Alex will lift him up to us from the open street. Also, keep an eye out for what you can use to better your chances.
des_raging_bull = "TranslationHere",--STATS : .44 Caliber : Six-shooter : High recoil$NL;Primarily developed for hunting big animals, the Bronco has found its use against heavily armored targets.$NL;With its .44 round, it packs a mean punch.
mission_slaughterhouse_prepare_ambush_hl = "TranslationHere",--Prepare for the ambush.
clip_amount_increase = "TranslationHere",--This upgrades the ammo clip amount for the GL40 Grenade Launcher.$NL;Why carry few ammo clips, when you can carry many?
mission_apartment_escape = "TranslationHere",--Get downstairs to the basement and escape through the sewers.
intro_hospital22 = "TranslationHere",--WOLF: Yeah yeah yeah. Run the plan!
mission_slaughterhouse_locate_van = "TranslationHere",--Get to the armored truck and blow it open.
location_str_end = "TranslationHere",--By the OVERKILL Cola sign.
location_hospital_ISOb = "TranslationHere",--Isolation B
mission_apartment_start = "TranslationHere",--Go through with the drug deal. This is the front that allows us to enter the building.
intro_hospital00 = "TranslationHere",--WOLF: Guys... it feels like something's in the air... money!
body_armor = "TranslationHere",--Body armor removes some of the damage received in combat.$NL;Good when moving between cover or in close combat.
intro_hospital18 = "TranslationHere",--Once I put on that damn dress, I tell ya; I'm smoking anywhere I want!
intro_hospital14 = "TranslationHere",--STRANGER: Hey, hold the door!
intro_street05_2 = "TranslationHere",--Open the god damn door Matt!
mission_suburbia_mission3_amount_text = "TranslationHere",--OF THE C4 CHARGES DEFUSED.
intro_hospital51 = "TranslationHere",--BAIN: You're breaking up - can you hear me OK?
intro_diamondheist01 = "TranslationHere",--Alright, entry point. Synchronize on my mark... Mark.
mission_slaughterhouse_prepare_gas = "TranslationHere",--Prepare one container with a can of gasoline.
mission_hospital_cooler_sub2 = "TranslationHere",--Second blood sample.
des_doctor_bag = "TranslationHere",--The doctor bag is deployable equipment. Once placed it can be interacted with by any player to fully restore health until depleted.
mission_apartment_door = "TranslationHere",--The panic room should be in a flat on the third floor.
intro_street02 = "TranslationHere",--No, that wasn't the plan. Don't change things up, man!
intro_hospital09 = "TranslationHere",--I'll pick you up from the roof when we're done.
mission_suburbia_mission9 = "TranslationHere",--Get down under the pool and into the printing shelter.
location_suburbia_m_house = "TranslationHere",--In Mitchell's House
mission_bridge_gear = "TranslationHere",--Get the scuba gear!
intro_hospital23 = "TranslationHere",--BAIN: Right...
mission_suburbia_mission1 = "TranslationHere",--Talk to Mitchell. See if you can get down to the basement without any necessary hustle.
location_panicroom = "TranslationHere",--In Panic Room.
mission_apartment_detach_hl = "TranslationHere",--Detach the panic room (Floor 2 and 3.)
des_body_armor = "TranslationHere",--Body armor absorbs more damage before the wearer get hurt. How much more depends on the upgrade level.
des_locked = "TranslationHere",--Gain cash and level up your reputation to unlock more weapons, equipment and crew bonuses.
tip_ammo_bag = "TranslationHere",--If you often run out of ammo, it might be a good idea to bring a bag of extra ammo. $NL; $NL; When ammo is running low, place the ammo bag on the ground and use it to refill your stash.
intro_secret_stash02 = "TranslationHere",--Alright, to repeat: Taxman is IRS, making a shady deal with some big corporation.
mission_escape_text = "TranslationHere",--Get down to the underground garage and make your escape.
mission_ap_c4_sub_btm = "TranslationHere",--Place the charges on floor 4.
intro_bridge02 = "TranslationHere",--Well, that oughta stop the prison transport, right? Let's get moving!
mission_get_into_bank_text = "TranslationHere",--Get inside and don't draw attention to yourselves!
mission_apartment_roof2_hl = "TranslationHere",--Defend Helicopter (Roof.)
intro_bridge03 = "TranslationHere",--Nice firework!
mission_escape = "TranslationHere",--Escape (Basement.)
mission_bridge_escort = "TranslationHere",--Escort the prisoner to the top of the right tower. When he's at the top, strap him down in the chair and send him skyward with the balloon.
mission_slaughterhouse_hide = "TranslationHere",--Hide the gold in the marked container.
mission_slaughterhouse_smoke_hl = "TranslationHere",--Start the smokescreen!
des_protector = "TranslationHere",--All your teammates get a health multiplier. The benefit of a Crew Bonus only applies to the three teammates of the one who equips it. This means that someone else on the team needs to equip a crew bonus in order for you to directly benefit from it. Multipliers do not stack if several teammates equip the same crew bonus.
des_three_angry_men = "TranslationHere",--Crowd control is more effective for all your teammates. The benefit of a Crew Bonus only applies to the three teammates of the one who equips it. This means that someone else on the team needs to equip a crew bonus in order for you to directly benefit from it. Multipliers do not stack if several teammates equip the same crew bonus.
des_ak47 = "TranslationHere",--STATS : 7.62mm : Automatic : Medium recoil$NL;Stick it to the man with the premiere choice amongst entrepeneurs and thugs alike. Simple Design, high reliability, low cost and so popular it is a part of a national flag - the AK was built to heist.
des_intimidation = "TranslationHere",--Supposed to give the owner an increased intimidation factor.
location_lobby = "TranslationHere",--In Lobby.
location_dh_canteen = "TranslationHere",--In Canteen.
location_dh_loot = "TranslationHere",--In Vault.
location_bridge_scaffhold_roof = "TranslationHere",--Top of the Tower.
location_slaughterhouse_fridgeroom = "TranslationHere",--In the Fridge Room.
location_suburbia_w_cellar = "TranslationHere",--In Wilson's Cellar
location_suburbia_w_house = "TranslationHere",--In Wilson's House
location_suburbia_m_fy = "TranslationHere",--At Mitchell's Front
doctor_bag = "TranslationHere",--The doctor bag can be deployed on the ground, so that you and your teamates can use it.$NL;It will help you help your friends.
sentry_gun_ammo_increase = "TranslationHere",--This upgrades the amount of ammo your sentry gun has, making it last longer.$NL;Outstanding. Now all we need is a deck of cards.
mission_suburbia_mission3_sub_4 = "TranslationHere",--Charge defused.
mission_suburbia_mission3_sub_7 = "TranslationHere",--Charge defused.
mission_suburbia_mission7_hl = "TranslationHere",--ATTACH THE C4 TO THE SAFE.
mission_suburbia_mission7 = "TranslationHere",--Attach the C4 to the safe using the hole you just drilled. Let the water and explosion force the safe open from within!
mission_suburbia_mission8 = "TranslationHere",--Cops might try to cut the water supply. Make sure the water is flowing!
mission_suburbia_mission12_hl = "TranslationHere",--INVESTIGATE THE SAFE.
mission_undercover_roof_hl = "TranslationHere",--PREPARATIONS.
mission_undercover_deal_hl = "TranslationHere",--DEAL GOING DOWN.
mission_undercover_shoot_limo = "TranslationHere",--Shoot at the cables snagging the limo to make it fall!
location_uc_stair2 = "TranslationHere",--At Right Staircase
mission_hospital_disguise = "TranslationHere",--Put on the doctors' outfits.
mission_hospital_drawblood_hl = "TranslationHere",--DRAW BLOOD FROM PATIENT.
mission_hospital_escape_hl = "TranslationHere",--ESCAPE!
mission_hospital_hatch_hl = "TranslationHere",--OPEN THE HATCH.
mission_hospital_hatch = "TranslationHere",--Open the hatch to get out of the elevator.
mission_hospital_waitElevator_hl = "TranslationHere",--WAIT FOR THE ELEVATOR.
location_hospital_reception = "TranslationHere",--Reception
location_hospital_Exam25 = "TranslationHere",--Examination C25
location_hospital_ExamE53 = "TranslationHere",--Examination E53
location_hospital_locker = "TranslationHere",--Locker room
location_hospital_staircase = "TranslationHere",--Staircase
location_hospital_ISOc = "TranslationHere",--Isolation C
location_hospital_Cafeteria = "TranslationHere",--Cafeteria
location_hospital_Entrance = "TranslationHere",--Elevators
location_hospital_Roof = "TranslationHere",--Roof
sa_title = "TranslationHere",--Do not translate.
intro_suburbia05 = "TranslationHere",--They bought it - let's drain the place!
intro_suburbia06 = "TranslationHere",--Suit up, load 'em, get to work!
intro_secret_stash = "TranslationHere",--6:00 pm, the District - Abandoned building
intro_secret_stash05 = "TranslationHere",--Crane ready.
intro_hospital = "TranslationHere",--8:24 pm, Mercy Hospital - Isolation ward
intro_hospital02 = "TranslationHere",--WOLF: Yeah yeah yeah. Run the plan!
intro_hospital06 = "TranslationHere",--You take out the cameras, keep the civilians down...
intro_hospital07 = "TranslationHere",--...and get me into the hospital patient database. We need to ID the right guy.
intro_hospital08 = "TranslationHere",--This should be quick and clean - security in hospitals is low.
intro_hospital10 = "TranslationHere",--WOLF: Guys... it feels like something's in the air... money!
intro_hospital15 = "TranslationHere",--"Please go outside and smoke - you can't smoke in here, sir!"
intro_hospital16 = "TranslationHere",--Bunch of crap...
intro_hospital19 = "TranslationHere",--WOLF: Bain, Old Time River here's been talking so I didn't quite catch that, but let's go.
intro_hospital29 = "TranslationHere",--WOLF: Bain, I didn't get a word of that, but fuck it - let's just do it.
intro_hospital30 = "TranslationHere",--WOLF: Guys... it feels like something's in the air... money!
intro_hospital41 = "TranslationHere",--BAIN: You're breaking up - can you hear me OK?
intro_hospital44 = "TranslationHere",--STRANGER: Hold that door!
intro_hospital45 = "TranslationHere",--This whole hospital can go to hell but do either of you have a light?
intro_hospital49 = "TranslationHere",--But let's just do it.
intro_hospital57 = "TranslationHere",--WOLF: Hey Bain, I'm sure you had a great plan - I just didn't fucking hear it!
intro_hospital58 = "TranslationHere",--But anyway, let's do it.
intro_hospital65 = "TranslationHere",--DALLAS: You! Get a move on!
intro_hospital66 = "TranslationHere",--STRANGER: Or what? You two gonna make an old man wait for the next one?
intro_hospital67 = "TranslationHere",--WOLF: Bain, I heard nada. This guy in the elevator kept messing it up!
intro_hospital68 = "TranslationHere",--Anyway, let's do it.
intro_hospital74 = "TranslationHere",--STRANGER: Hey, hold the door!
intro_hospital78 = "TranslationHere",--WOLF: Hey Bain, great briefing. I heard jack shit.
intro_hospital79 = "TranslationHere",--Let's just, ah... Play by ear.
intro_hospital80 = "TranslationHere",--WOLF: Guys... it feels like something's in the air... money!
intro_hospital84 = "TranslationHere",--STRANGER: Hang on! Hang on!! WOLF: Good day sir...
intro_hospital87 = "TranslationHere",--WOLF: Bain, all I heard was:
intro_hospital93 = "TranslationHere",--BAIN: Right...
intro_hospital94 = "TranslationHere",--STRANGER: Hold the door, hold the door.
intro_hospital96 = "TranslationHere",--What do you two do?! Sell insurance?
intro_hospital101 = "TranslationHere",--BAIN: You're breaking up - can you hear me OK?
intro_hospital104 = "TranslationHere",--STRANGER: Hooold the door! WOLF: Good day, sir...
intro_hospital108 = "TranslationHere",--*cough* *cough* I feel terrible...
intro_hospital110 = "TranslationHere",--WOLF: Guys... it feels like something's in the air... money!
intro_hospital111 = "TranslationHere",--BAIN: You're breaking up - can you hear me OK?
intro_hospital112 = "TranslationHere",--WOLF: Yeah yeah yeah. Run the plan!
intro_hospital116 = "TranslationHere",--Kids these days - I swear, no manners.
intro_hospital121 = "TranslationHere",--BAIN: You're breaking up - can you hear me OK?
intro_hospital123 = "TranslationHere",--BAIN: Right...
intro_hospital125 = "TranslationHere",--WOLF: Yeah, come on in...
intro_hospital126 = "TranslationHere",--Ay, thank you!
intro_hospital130 = "TranslationHere",--WOLF: Guys... it feels like something's in the air... money!
intro_hospital131 = "TranslationHere",--BAIN: You're breaking up - can you hear me OK?
intro_hospital133 = "TranslationHere",--BAIN: Right...
intro_hospital135 = "TranslationHere",--WOLF (in Swedish): Ah nä men... Det finns ju hur mycket plats som helst i den här jävla hissjäveln.
intro_hospital136 = "TranslationHere",--STRANGER: Ah, thank you.
intro_hospital139 = "TranslationHere",--WOLF: Man, this guy can't stop talkin! Yap yap yap!
intro_hospital140 = "TranslationHere",--WOLF: Guys... it feels like something's in the air... money!
intro_hospital141 = "TranslationHere",--BAIN: You're breaking up - can you hear me OK?
