ch_eagle_eyes = "TranslationHere",--Point out a special enemy using the "shout out" command.
ch_stand_together_hl = "TranslationHere",--Stand together
ch_revive_3_hl = "TranslationHere",--A helping hand III
ch_beretta92_vs_the_law_4_hl = "TranslationHere",--B9-S VS. the Law IV
ch_bomb_man_hl = "TranslationHere",--Bomb man
ch_eagle_eyes_hl = "TranslationHere",--Eagle eyes
ch_bleed_out_kill_1_hl = "TranslationHere",--Wait, I'm not dead yet! I
ch_revive = "TranslationHere",--Revive or uncuff any teammate ##revive## times.
ch_ak47_vs_the_law_5_hl = "TranslationHere",--AK VS. the Law V
ch_aquire_money_5_hl = "TranslationHere",--...and that's a lot of cash V
ch_revive_1_hl = "TranslationHere",--A helping hand I
ch_quad_tripmine = "TranslationHere",--Defeat four Law enforcers with a single Trip Mine.
ch_revive_4_hl = "TranslationHere",--A helping hand IV
ch_last_man_standing = "TranslationHere",--Beat a heist after having been the only one alive. (4 teammates).
ch_m4_head_shots_3_hl = "TranslationHere",--Amcar-4 expert III
ch_aquire_money_1_hl = "TranslationHere",--...and that's a lot of cash I
ch_suburbia_no_bleedouts_hl = "TranslationHere",--COUNTERFEIT: Bulletproof
ch_m14_vs_the_law_1_hl = "TranslationHere",--M308 VS. the Law I
ch_beretta92_vs_the_law_1_hl = "TranslationHere",--B9-S VS. the Law I
ch_reinbeck_spooc_kill = "TranslationHere",--Using the Reinbeck 880, defeat ##reinbeck_spooc_kill## Cloakers. Using Melee does not count towards this challenge!
ch_mossberg_head_shots_1_hl = "TranslationHere",--Locomotive 12G expert I
ch_hk21_head_shots = "TranslationHere",--Using the Brenner 21, defeat ##hk21_law_head_shot## Law enforcers with headshots. Using Melee does not count towards this challenge!
ch_aquire_money_10 = "TranslationHere",--Acquire $1,000,000,000 in cash.
ch_bridge_no_civilians_hl = "TranslationHere",--Green Bridge: Clean hit
ch_quick_gold = "TranslationHere",--Beat SLAUGHTERHOUSE within 15 minutes, taking all the gold. To complete this challenge, you will have to have played the heist from the start.
ch_slaughterhouse_overkill_no_trade = "TranslationHere",--Complete Slaughterhouse on OVERKILL difficulty without anyone getting traded from custody.
ch_bank_no_bleedouts_hl = "TranslationHere",--First World Bank: Bulletproof
ch_me_vs_tank = "TranslationHere",--Defeat ##tank_kill## Bulldozers.  Using Trip Mines or Melee does not count towards this challenge!
ch_apartment_on_overkill_145_hl = "TranslationHere",--Brush with death
ch_secret_stash_no_deaths_hl = "TranslationHere",--UNDERCOVER: Like a pro
ch_meat_packing = "TranslationHere",--Stay inside THE MAIN ROOM in SLAUGHTERHOUSE for an hour or more. To complete this challenge, you will have to have played the heist from the start.
ch_m4_vs_the_law_2_hl = "TranslationHere",--Amcar-4 VS. the Law II
ch_mp5_head_shots = "TranslationHere",--Using the Compact-5, defeat ##mp5_law_head_shot## Law enforcers with headshots. Using Melee does not count towards this challenge!
ch_m4_head_shots_4_hl = "TranslationHere",--Amcar-4 expert IV
ch_mossberg_vs_the_law_1_hl = "TranslationHere",--Locomotive 12G VS. the Law I
ch_glock_vs_the_law_4_hl = "TranslationHere",--STRYK VS. the Law IV
ch_cheney = "TranslationHere",--Defeat a Bulldozer with a shotgun.
ch_mac11_heavy_swat_kill_1_hl = "TranslationHere",--Mark 11 VS. Heavy SWATS
ch_intimidating = "TranslationHere",--Get a Heavy SWAT to give up.
ch_street_no_bleedouts_hl = "TranslationHere",--Heat Street: Bulletproof
ch_aquire_money_9_hl = "TranslationHere",--...and that's a lot of cash IX
ch_me_vs_the_law = "TranslationHere",--Defeat ##law_kill## Law enforcers.  Using Trip Mines or Melee does not count towards this challenge!
ch_cant_touch = "TranslationHere",--Beat HEAT STREET on OVERKILL difficulty, with your group accuracy being at 60% or higher. To complete this challenge, everyone in your crew will have to have played the heist from the start.
ch_duck_hunting_hl = "TranslationHere",--A bridge too far!
ch_diplomatic = "TranslationHere",--Perform a hostage trade.
ch_street_no_civilians_hl = "TranslationHere",--Heat Street: Clean hit
ch_c45_vs_the_law_3_hl = "TranslationHere",--Crosskill .45 VS. the Law III
ch_m4_spooc_head_shot = "TranslationHere",--Using the Amcar-4, defeat ##m4_spooc_head_shot## Cloakers with headshots. Using Melee does not count towards this challenge!
ch_golden_boy = "TranslationHere",--Beat all original heists on OVERKILL 145+ difficulty and show them all you are on top! Completing this will make you golden!
ch_bridge_overkill_no_trade_hl = "TranslationHere",--Green Bridge: Don't lose face
ch_mossberg_vs_the_law_6_hl = "TranslationHere",--Locomotive 12G VS. the Law VI
ch_street_on_overkill = "TranslationHere",--Complete Heat Street on OVERKILL difficulty.
ch_mossberg_cop_kill = "TranslationHere",--Using the Locomotive 12G, defeat ##mossberg_cop_kill## Cops. Using Melee does not count towards this challenge!
ch_glock_head_shots_4_hl = "TranslationHere",--STRYK VS. the Law Headshot IV
ch_bank_no_deaths = "TranslationHere",--Complete First World Bank on hard difficulty without being taken into custody.
ch_meat_packing_hl = "TranslationHere",--Meat packin'
ch_m4_vs_the_law_3_hl = "TranslationHere",--Amcar-4 VS. the Law III
ch_intimidating_hl = "TranslationHere",--Intimidating
ch_cant_touch_hl = "TranslationHere",--Easy street
ch_mp5_shield_head_shot = "TranslationHere",--Using the Compact-5, defeat ##mp5_shield_head_shot## Shields with headshots. Using Melee does not count towards this challenge!
ch_suburbia_on_overkill_hl = "TranslationHere",--COUNTERFEIT: OVERKILL
ch_golden_boy_hl = "TranslationHere",--You are GOLDEN! OVERKILL salutes you!
ch_m79_simultaneous_kills_3_hl = "TranslationHere",--GL40 Cluster Kill III
ch_me_vs_the_law_head_shot = "TranslationHere",--Defeat ##law_head_shot## Law enforcers with headshots. Using Melee does not count towards this challenge!
ch_trip_mine_vs_the_law_4_hl = "TranslationHere",--Trip Mines VS. the Law IV
ch_melee = "TranslationHere",--Defeat ##melee_law_kill## Law enforcers with melee attacks.
ch_take_sapphires_hl = "TranslationHere",--Are those the blue ones?
ch_reinbeck_head_shots_3_hl = "TranslationHere",--Reinbeck 880 expert III
ch_mossberg_head_shots_4_hl = "TranslationHere",--Locomotive 12G expert IV
ch_cheney_hl = "TranslationHere",--Cheney?
ch_hk21_head_shots_1_hl = "TranslationHere",--Brenner 21 expert I
ch_m79_simultaneous_kills_4_hl = "TranslationHere",--GL40 Cluster Kill IV
ch_reinbeck_head_shots_4_hl = "TranslationHere",--Reinbeck 880 expert IV
ch_hos_afraid_of_the_dark = "TranslationHere",--In NO MERCY, get the power back up within 5 seconds of it being shut down. To complete this challenge, you will have to have played the heist from the start.
ch_bronco_tank_kill_1_hl = "TranslationHere",--Bronco .44 VS. Bulldozers
ch_stand_together = "TranslationHere",--Beat HEAT STREET on normal difficulty or above without anyone getting downed. To complete this challenge, you will have to have played the heist from the start.
ch_beretta92_vs_the_law_2_hl = "TranslationHere",--B9-S VS. the Law II
ch_hk21_head_shots_4_hl = "TranslationHere",--Brenner 21 expert IV
ch_beretta92_head_shots_3_hl = "TranslationHere",--B9-S expert III
ch_glock_head_shots = "TranslationHere",--Using the STRYK, defeat ##glock_law_head_shot## Law enforcers with headshots. Using Melee does not count towards this challenge!
ch_hk21_head_shots_3_hl = "TranslationHere",--Brenner 21 expert III
ch_mp5_vs_the_law_1_hl = "TranslationHere",--Compact-5 VS. the Law I
ch_mac11_vs_the_law_6_hl = "TranslationHere",--Mark 11 VS. the Law VI
ch_reinbeck_vs_the_law_4_hl = "TranslationHere",--Reinbeck 880 VS. the Law IV
ch_reinbeck_vs_the_law_6_hl = "TranslationHere",--Reinbeck 880 VS. the Law VI
ch_hk21_shield_kill_1_hl = "TranslationHere",--Brenner 21 VS. Shields
ch_payday = "TranslationHere",--Aquire one billion dollars in total cash. One. BILLION. Dollars.
ch_tiedown_civilian_hl = "TranslationHere",--Don't go anywhere!
ch_civil_disobedience_hl = "TranslationHere",--Civil disobedience
ch_tris_tripmine_hl = "TranslationHere",--Three guys went on a Trip
ch_bank_no_civilians = "TranslationHere",--Complete First World Bank on hard difficulty without killing any civilians.
ch_bronco_vs_the_law_1_hl = "TranslationHere",--Bronco .44 VS. the Law I
ch_mossberg_head_shots = "TranslationHere",--Using the Locomotive 12G, defeat ##mossberg_law_head_shot## Law enforcers with headshots. Using Melee does not count towards this challenge!
ch_melee_2_hl = "TranslationHere",--Saving bullets II
ch_the_darkness = "TranslationHere",--On GREEN BRIDGE, destroy all the lights in the main scaffolding tower. To complete this challenge, you will have to have played the heist from the start.
ch_aquire_money_7_hl = "TranslationHere",--...and that's a lot of cash VII
ch_me_vs_the_law_head_shot_3_hl = "TranslationHere",--Me VS. the Law Headshot III
ch_diamond_heist_no_deaths = "TranslationHere",--Complete Diamond Heist on hard difficulty without being taken into custody.
ch_secret_stash_no_bleedouts = "TranslationHere",--Complete UNDERCOVER on hard difficulty without going into bleedout.
ch_me_vs_spooc = "TranslationHere",--Defeat ##spooc_kill## Cloakers. Using Trip Mines or Melee does not count towards this challenge!
ch_mp5_head_shots_1_hl = "TranslationHere",--Compact-5 expert I
ch_reinbeck_head_shots_2_hl = "TranslationHere",--Reinbeck 880 expert II
ch_aquire_money_5 = "TranslationHere",--Acquire $300,000,000 in cash.
ch_me_vs_fbi_hl = "TranslationHere",--Me VS. FBI Agents
ch_dont_lose_face_hl = "TranslationHere",--Don't lose face
ch_suburbia_on_overkill_145 = "TranslationHere",--Complete COUNTERFEIT on OVERKILL 145+ difficulty.
ch_me_vs_the_law_head_shot_5_hl = "TranslationHere",--Me VS. the Law Headshot V
ch_suburbia_no_deaths = "TranslationHere",--Complete COUNTERFEIT on hard difficulty, without being taken into custody.
ch_m79_simultaneous_specials_1_hl = "TranslationHere",--GL40 Special Treat
ch_deploy_ammobag_hl = "TranslationHere",--Ammo provider
ch_apartment_overkill_no_trade_hl = "TranslationHere",--Panic Room: Don't lose face
ch_slaughterhouse_no_bleedouts_hl = "TranslationHere",--Slaughterhouse: Bulletproof
ch_bullet_to_bleed_out_hl = "TranslationHere",--Down, but not dead
ch_christmas_present = "TranslationHere",--In multiplayer, find a Xmas present on any level.
ch_saviour_hl = "TranslationHere",--Saviour
ch_glock_head_shots_1_hl = "TranslationHere",--STRYK VS. the Law Headshot I
ch_c45_head_shots_1_hl = "TranslationHere",--Crosskill .45 expert I
ch_beretta92_taser_kill = "TranslationHere",--Using the B9-S, defeat ##beretta92_taser_kill## tasers. Using Melee does not count towards this challenge!
ch_m14_vs_the_law_3_hl = "TranslationHere",--M308 VS. the Law III
ch_me_vs_cop_hl = "TranslationHere",--Me VS. the Cops
ch_me_vs_heavy_swat = "TranslationHere",--Defeat ##heavy_swat_kill## Heavy SWAT. Using Trip Mines or Melee does not count towards this challenge!
ch_reinbeck_spooc_kill_1_hl = "TranslationHere",--Reinbeck 880 VS. Cloakers
ch_diamond_heist_no_civilians_hl = "TranslationHere",--Diamond Heist: Clean hit
ch_got_your_back = "TranslationHere",--Get traded for a hostage in your first game.
ch_hk21_vs_the_law_3_hl = "TranslationHere",--Brenner 21 VS. the Law III
ch_akimbo = "TranslationHere",--Get a secondary weapon.
ch_one_shot_one_kill_hl = "TranslationHere",--One shot, one kill - repeat
ch_m79_vs_the_law_5_hl = "TranslationHere",--GL40 VS. the Law V
ch_apartment_on_overkill = "TranslationHere",--Complete Panic Room on OVERKILL difficulty.
ch_bleed_out_kill_4_hl = "TranslationHere",--Wait, I'm not dead yet! IV
ch_diamond_heist_no_bleedouts = "TranslationHere",--Complete Diamond Heist on hard difficulty without going into bleedout.
ch_m14_vs_the_law = "TranslationHere",--Using the M308, defeat ##m14_law_kill## Law enforcers. Using Melee does not count towards this challenge!
ch_pacifist_hl = "TranslationHere",--Pacifist
ch_street_no_deaths = "TranslationHere",--Complete Heat Street on hard difficulty without being taken into custody.
ch_bank_no_civilians_hl = "TranslationHere",--First World Bank: Clean hit
ch_bleed_out_multikill_hl = "TranslationHere",--Legendary last stand
ch_bank_on_overkill_145_hl = "TranslationHere",--Bank on me
ch_slaughterhouse_on_overkill = "TranslationHere",--Complete Slaughterhouse on OVERKILL difficulty.
ch_bronco_head_shots_3_hl = "TranslationHere",--Bronco .44 expert III
ch_apartment_on_overkill_hl = "TranslationHere",--Panic Room: OVERKILL
ch_m14_head_shots_1_hl = "TranslationHere",--M308 expert I
ch_bleed_out_kill_3_hl = "TranslationHere",--Wait, I'm not dead yet! III
ch_windowlicker_hl = "TranslationHere",--Windowlicker
ch_bridge_no_deaths = "TranslationHere",--Complete Green Bridge on hard difficulty without being taken into custody.
ch_tiedown_cop_hl = "TranslationHere",--Owning the Police
ch_c45_vs_the_law = "TranslationHere",--Using the Crosskill, defeat ##c45_law_kill## Law enforcers. Using Melee does not count towards this challenge!
ch_me_vs_tank_hl = "TranslationHere",--Me VS. Bulldozers
ch_mac11_head_shots_3_hl = "TranslationHere",--Mark 11 expert III
ch_dodge_this_hl = "TranslationHere",--Dodge this!
ch_glock_vs_the_law = "TranslationHere",--Using the STRYK, defeat ##glock_law_kill## Law enforcers. Using Melee does not count towards this challenge!
ch_mp5_shield_head_shot_1_hl = "TranslationHere",--Compact-5 VS. Shields
ch_hk21_vs_the_law_1_hl = "TranslationHere",--Brenner 21 VS. the Law I
ch_secret_stash_no_bleedouts_hl = "TranslationHere",--UNDERCOVER: Bulletproof
ch_m79_vs_the_law_1_hl = "TranslationHere",--GL40 VS. the Law I
ch_me_vs_the_law_head_shot_2_hl = "TranslationHere",--Me VS. the Law Headshot II
ch_ready_yet_hl = "TranslationHere",--Are you ready yet?
ch_mp5_vs_the_law_5_hl = "TranslationHere",--Compact-5 VS. the Law V
ch_diplomatic_hl = "TranslationHere",--Diplomatic
ch_apartment_no_bleedouts_hl = "TranslationHere",--Panic Room: Bulletproof
ch_overkill = "TranslationHere",--Do it all!
ch_sentry_gun_vs_the_law_2_hl = "TranslationHere",--SENTRY GUN VS. the Law II
ch_m79_vs_the_law = "TranslationHere",--Using the GL40, defeat ##m79_law_kill## Law enforcers. Using Melee does not count towards this challenge!
ch_mossberg_vs_the_law_3_hl = "TranslationHere",--Locomotive 12G VS. the Law III
ch_me_vs_the_law_head_shot_4_hl = "TranslationHere",--Me VS. the Law Headshot IV
ch_bridge_no_civilians = "TranslationHere",--Complete Green Bridge on hard difficulty without killing any civilians.
ch_kill_cameras_hl = "TranslationHere",--No photos
ch_reinbeck_head_shots = "TranslationHere",--Using the Reinbeck 880, defeat ##reinbeck_law_head_shot## Law enforcers with headshots. Using Melee does not count towards this challenge!
ch_payday_cat_hl = "TranslationHere",--PAYDAY: The Heist
ch_me_vs_taser_hl = "TranslationHere",--Me VS. Tasers
ch_sentry_gun_row_kills = "TranslationHere",--Using the SENTRY GUN, defeat ##sentry_gun_law_row_kills## Law enforcers in a row.
ch_slaughterhouse_no_deaths = "TranslationHere",--Complete Slaughterhouse on hard difficulty without being taken into custody.
ch_grim_reaper = "TranslationHere",--Defeat a Law enforcer while you're in custody.
ch_m4_vs_the_law = "TranslationHere",--Using the Amcar-4, defeat ##m4_law_kill## Law enforcers. Using Melee does not count towards this challenge!
ch_diamond_heist_on_overkill = "TranslationHere",--Complete Diamond Heist on OVERKILL difficulty.
ch_bridge_on_overkill_145 = "TranslationHere",--Beat GREEN BRIDGE on OVERKILL 145+ difficulty. To complete this challenge, you will have to have played the heist from the start.
ch_slaughterhouse_on_overkill_hl = "TranslationHere",--Slaughterhouse: OVERKILL
ch_mp5_head_shots_2_hl = "TranslationHere",--Compact-5 expert II
ch_plant_tripmine_hl = "TranslationHere",--Trip Mine plantation
ch_aquire_money_6 = "TranslationHere",--Acquire $400,000,000 in cash.
ch_mossberg_head_shots_3_hl = "TranslationHere",--Locomotive 12G expert III
ch_ak47_vs_the_law_4_hl = "TranslationHere",--AK VS. the Law IV
ch_revived_hl = "TranslationHere",--Thanks, I owe you one!
ch_m4_head_shots_1_hl = "TranslationHere",--Amcar-4 expert I
ch_grim_reaper_hl = "TranslationHere",--Grim reaper
ch_chavez_can_run_hl = "TranslationHere",--You can run but you can't hide
ch_c45_vs_the_law_6_hl = "TranslationHere",--Crosskill .45 VS. the Law VI
ch_diamond_heist_overkill_no_trade = "TranslationHere",--Complete Diamond Heist on OVERKILL difficulty without anyone getting traded from custody.
ch_melee_3_hl = "TranslationHere",--Saving bullets III
ch_left_for_dead_hl = "TranslationHere",--Left for dead
ch_one_shot_one_kill = "TranslationHere",--Get 30 kills using 30 shots, using only the M308 Rifle.
ch_slaughterhouse_no_civilians_hl = "TranslationHere",--Slaughterhouse: Clean hit
ch_bank_on_overkill_145 = "TranslationHere",--Beat FIRST WORLD BANK on OVERKILL 145+ difficulty. To complete this challenge, you will have to have played the heist from the start.
ch_m4_head_shots = "TranslationHere",--Using the Amcar-4, defeat ##m4_law_head_shot## Law enforcers with headshots. Using Melee does not count towards this challenge!
ch_mossberg_vs_the_law_2_hl = "TranslationHere",--Locomotive 12G VS. the Law II
ch_aquire_money_9 = "TranslationHere",--Acquire $800,000,000 in cash.
ch_m14_head_shots_4_hl = "TranslationHere",--M308 expert IV
ch_bronco_head_shots_2_hl = "TranslationHere",--Bronco .44 expert II
ch_me_vs_cop = "TranslationHere",--Defeat ##cop_kill## Cops. Using Trip Mines or Melee does not count towards this challenge!
ch_blow_out_hl = "TranslationHere",--Blow-out
ch_c45_head_shots = "TranslationHere",--Using the Crosskill, defeat ##c45_law_head_shot## Law enforcers with headshots. Using Melee does not count towards this challenge!
ch_sentry_gun_row_kills_1_hl = "TranslationHere",--SENTRY GUN Kills in a Row I
ch_mac11_heavy_swat_kill = "TranslationHere",--Using the Mark 11, defeat ##mac11_heavy_swat_kill## Heavy SWATS. Using Melee does not count towards this challenge!
ch_m4_vs_the_law_6_hl = "TranslationHere",--Amcar-4 VS. the Law VI
ch_c45_vs_the_law_4_hl = "TranslationHere",--Crosskill .45 VS. the Law IV
ch_suburbia_on_overkill = "TranslationHere",--Complete COUNTERFEIT on OVERKILL difficulty.
ch_bridge_overkill_no_trade = "TranslationHere",--Complete Green Bridge on OVERKILL difficulty without anyone getting traded from custody.
ch_slaughterhouse_no_civilians = "TranslationHere",--Complete Slaughterhouse on hard difficulty without killing any civilians.
ch_the_darkness_hl = "TranslationHere",--Darkness
ch_bleed_out_kill_2_hl = "TranslationHere",--Wait, I'm not dead yet! II
ch_blood_in_blood_out_hl = "TranslationHere",--Blood in, blood out
ch_c45_head_shots_2_hl = "TranslationHere",--Crosskill .45 expert II
ch_bronco_vs_the_law_5_hl = "TranslationHere",--Bronco .44 VS. the Law V
ch_me_vs_heavy_swat_hl = "TranslationHere",--Me VS. Heavy SWAT
ch_dozen_angry_hl = "TranslationHere",--I pushed the button and lived!
ch_street_overkill_no_trade_hl = "TranslationHere",--Heat Street: Don't lose face
ch_me_vs_fbi = "TranslationHere",--Defeat ##fbi_kill## FBI Agents. Using Trip Mines or Melee does not count towards this challenge!
ch_never_downed_hl = "TranslationHere",--Flawless
ch_mossberg_head_shots_2_hl = "TranslationHere",--Locomotive 12G expert II
ch_bronco_vs_the_law_6_hl = "TranslationHere",--Bronco .44 VS. the Law VI
ch_m14_head_shots = "TranslationHere",--Using the M308, defeat ##m14_law_head_shot## Law enforcers with headshots. Using Melee does not count towards this challenge!
ch_reinbeck_vs_the_law_2_hl = "TranslationHere",--Reinbeck 880 VS. the Law II
ch_m79_simultaneous_kills = "TranslationHere",--Using the GL40, defeat ##m79_law_simultaneous_kills## Law enforcers simultaneously.
ch_m4_vs_the_law_4_hl = "TranslationHere",--Amcar-4 VS. the Law IV
ch_m14_head_shots_3_hl = "TranslationHere",--M308 expert III
ch_mp5_head_shots_4_hl = "TranslationHere",--Compact-5 expert IV
ch_me_vs_spooc_hl = "TranslationHere",--Me VS. Cloakers
ch_aquire_money_2 = "TranslationHere",--Acquire $50,000,000 in cash.
ch_tiedown_swat = "TranslationHere",--Force ##tiedown_swat## blue SWATs to cuff themselves.
ch_bullet_to_bleed_out = "TranslationHere",--Go into bleedout from enemy fire.
ch_crowd_control = "TranslationHere",--Beat COUNTERFEIT without letting any hostage escape or die. To complete this challenge, you will have to have played the heist from the start.
ch_bank_overkill_no_trade_hl = "TranslationHere",--First World Bank: Don't lose face
ch_diamond_heist_no_civilians = "TranslationHere",--Complete Diamond Heist on hard difficulty without killing any civilians.
ch_take_sapphires = "TranslationHere",--Steal all the sapphires in DIAMOND HEIST on hard or OVERKILL difficulty. To complete this challenge, you will have to have played the heist from the start.
ch_ninja_hl = "TranslationHere",--Shinobi
ch_civil_disobedience = "TranslationHere",--Defeat 100 law enforcers in a single heist.
ch_mac11_vs_the_law_1_hl = "TranslationHere",--Mark 11 VS. the Law I
ch_secret_stash_on_overkill_hl = "TranslationHere",--UNDERCOVER: OVERKILL
ch_beretta92_head_shots_4_hl = "TranslationHere",--B9-S expert IV
ch_aquire_money_7 = "TranslationHere",--Acquire $500,000,000 in cash.
ch_trip_mine_vs_the_law_2_hl = "TranslationHere",--Trip Mines VS. the Law II
ch_suburbia_no_bleedouts = "TranslationHere",--Complete COUNTERFEIT on hard difficulty without going into bleedout.
ch_bank_no_bleedouts = "TranslationHere",--Complete First World Bank heist on hard difficulty without going into bleedout.
ch_bridge_no_bleedouts_hl = "TranslationHere",--Green Bridge: Bulletproof
ch_never_downed = "TranslationHere",--Complete one entire successful session without getting downed.
ch_citys_finest_hl = "TranslationHere",--The city's finest
ch_mac11_vs_the_law_5_hl = "TranslationHere",--Mark 11 VS. the Law V
ch_apartment_no_civilians_hl = "TranslationHere",--Panic Room: Clean hit
ch_diamond_heist_overkill_no_trade_hl = "TranslationHere",--Diamond Heist: Don't lose face
ch_me_vs_taser = "TranslationHere",--Defeat ##taser_kill## Tasers. Using Trip Mines or Melee does not count towards this challenge!
ch_aquire_money_10_hl = "TranslationHere",--...and that's a lot of cash X
ch_trip_mine_vs_the_law = "TranslationHere",--Defeat ##trip_mine_law_kill## Law enforcers using your Trip Mines. Using Melee does not count towards this challenge!
ch_trip_mine_vs_the_law_3_hl = "TranslationHere",--Trip Mines VS. the Law III
ch_aquire_money_2_hl = "TranslationHere",--...and that's a lot of cash II
ch_glock_vs_the_law_1_hl = "TranslationHere",--STRYK VS. the Law I
ch_mp5_vs_the_law = "TranslationHere",--Using the Compact-5, defeat ##mp5_law_kill## Law enforcers. Using Melee does not count towards this challenge!
ch_m14_taser_head_shot = "TranslationHere",--Using the M308, defeat ##m14_taser_head_shot## Tasers with headshots. Using Melee does not count towards this challenge!
ch_mac11_vs_the_law = "TranslationHere",--Using the Mark 11, defeat ##mac11_law_kill## Law enforcers. Using Melee does not count towards this challenge!
ch_beretta92_taser_kill_1_hl = "TranslationHere",--B9-S VS. Tasers
ch_aquire_money_8 = "TranslationHere",--Acquire $600,000,000 in cash.
ch_payday_hl = "TranslationHere",--PAYDAY
ch_street_overkill_no_trade = "TranslationHere",--Complete Heat Street on OVERKILL difficulty without anyone getting traded from custody.
ch_apartment_no_deaths_hl = "TranslationHere",--Panic Room: Like a pro
ch_m4_vs_the_law_1_hl = "TranslationHere",--Amcar-4 VS. the Law I
ch_c45_fbi_kill = "TranslationHere",--Using the Crosskill, defeat ##c45_fbi_kill## FBI agents. Using Melee does not count towards this challenge!
ch_aquire_money_4_hl = "TranslationHere",--...and that's a lot of cash IV
ch_bridge_on_overkill_145_hl = "TranslationHere",--Beat the shield
ch_m4_head_shots_2_hl = "TranslationHere",--Amcar-4 expert II
ch_me_vs_the_law_head_shot_1_hl = "TranslationHere",--Me VS. the Law Headshot I
ch_m14_vs_the_law_2_hl = "TranslationHere",--M308 VS. the Law II
ch_trip_mine_vs_the_law_1_hl = "TranslationHere",--Trip Mines VS. the Law I
ch_beretta92_vs_the_law_3_hl = "TranslationHere",--B9-S VS. the Law III
ch_suburbia_no_deaths_hl = "TranslationHere",--COUNTERFEIT: Like a pro
ch_bridge_on_overkill_hl = "TranslationHere",--Green Bridge: OVERKILL
ch_mac11_vs_the_law_3_hl = "TranslationHere",--Mark 11 VS. the Law III
ch_mac11_vs_the_law_2_hl = "TranslationHere",--Mark 11 VS. the Law II
ch_ninja = "TranslationHere",--Bypassing all 3 consoles before raising the alarm, beat DIAMOND HEIST on hard or OVERKILL difficulty. To complete this challenge, you will have to have played the heist from the start.
ch_c45_vs_the_law_2_hl = "TranslationHere",--Crosskill .45 VS. the Law II
ch_me_vs_the_law_1_hl = "TranslationHere",--Me VS. the Law I
ch_dodge_this = "TranslationHere",--Beat a heist on normal difficulty or above, having killed a Bulldozer without taking damage from any Bulldozer. To complete this challenge, you will have to have played the heist from the start.
ch_dual_tripmine_hl = "TranslationHere",--Two guys went on a Trip
ch_ak47_vs_the_law_2_hl = "TranslationHere",--AK VS. the Law II
ch_bank_on_overkill = "TranslationHere",--Complete First World Bank on OVERKILL difficulty.
ch_hk21_vs_the_law_6_hl = "TranslationHere",--Brenner 21 VS. the Law VI
ch_hk21_vs_the_law = "TranslationHere",--Using the Brenner 21, defeat ##hk21_law_kill## Law enforcers. Using Melee does not count towards this challenge!
ch_m4_vs_the_law_5_hl = "TranslationHere",--Amcar-4 VS. the Law V
ch_tiedown_law = "TranslationHere",--Force ##tiedown_law## Law enforcers to cuff themselves.
ch_revive_2_hl = "TranslationHere",--A helping hand II
ch_glock_vs_the_law_3_hl = "TranslationHere",--STRYK VS. the Law III
ch_plant_tripmine = "TranslationHere",--Plant ##plant_tripmine## Trip Mines.
ch_aquire_money_8_hl = "TranslationHere",--...and that's a lot of cash VIII
ch_last_man_standing_hl = "TranslationHere",--Last man standing
ch_mp5_vs_the_law_2_hl = "TranslationHere",--Compact-5 VS. the Law II
ch_aquire_money_3_hl = "TranslationHere",--...and that's a lot of cash III
ch_ak47_head_shots_3_hl = "TranslationHere",--AK VS. the Law Headshot III
ch_fall_to_bleed_out = "TranslationHere",--Go into bleedout from fall damage.
ch_bank_on_overkill_hl = "TranslationHere",--First World Bank: OVERKILL
ch_beretta92_head_shots_2_hl = "TranslationHere",--B9-S expert II
ch_mossberg_vs_the_law_5_hl = "TranslationHere",--Locomotive 12G VS. the Law V
ch_secret_stash_on_overkill = "TranslationHere",--Complete UNDERCOVER on OVERKILL difficulty.
ch_m79_simultaneous_kills_1_hl = "TranslationHere",--GL40 Cluster Kill I
ch_tiedown_swat_hl = "TranslationHere",--Owning the blue SWAT
ch_slaughterhouse_on_overkill_145 = "TranslationHere",--Beat SLAUGHTERHOUSE on OVERKILL 145+ difficulty. To complete this challenge, you will have to have played the heist from the start.
ch_mac11_head_shots_1_hl = "TranslationHere",--Mark 11 expert I
ch_diamond_heist_on_overkill_hl = "TranslationHere",--Diamond Heist: OVERKILL
ch_me_vs_shield = "TranslationHere",--Defeat ##shield_kill## Shields. Using Trip Mines or Melee does not count towards this challenge!
ch_reinbeck_vs_the_law_1_hl = "TranslationHere",--Reinbeck 880 VS. the Law I
ch_mp5_head_shots_3_hl = "TranslationHere",--Compact-5 expert III
ch_apartment_no_civilians = "TranslationHere",--Complete Panic Room on hard difficulty without killing any civilians.
ch_m79_vs_the_law_2_hl = "TranslationHere",--GL40 VS. the Law II
ch_hos_cut_wire = "TranslationHere",--In NO MERCY, cut the correct wire opening the ICU door security system. To complete this challenge, you will have to have played the heist from the start.
ch_sentry_gun_row_kills_4_hl = "TranslationHere",--SENTRY GUN Kills in a Row IV
ch_tiedown_law_hl = "TranslationHere",--Owning the Law
ch_melee_1_hl = "TranslationHere",--Saving bullets I
ch_me_vs_the_law_3_hl = "TranslationHere",--Me VS. the Law III
ch_dual_tripmine = "TranslationHere",--Defeat two Law enforcers with a single Trip Mine.
ch_me_vs_swat_hl = "TranslationHere",--Me VS. blue SWAT
ch_m14_head_shots_2_hl = "TranslationHere",--M308 expert II
ch_bronco_vs_the_law_4_hl = "TranslationHere",--Bronco .44 VS. the Law IV
ch_hot_lava_hl = "TranslationHere",--Hot lava
ch_c45_head_shots_3_hl = "TranslationHere",--Crosskill .45 expert III
ch_beretta92_vs_the_law_6_hl = "TranslationHere",--B9-S VS. the Law VI
ch_arrested_single = "TranslationHere",--Get arrested.
ch_secret_stash_no_deaths = "TranslationHere",--Complete UNDERCOVER on hard difficulty without being taken into custody.
ch_me_vs_shield_hl = "TranslationHere",--Me VS. Shields
ch_beretta92_head_shots = "TranslationHere",--Using the B9-S, defeat ##beretta92_law_head_shot## Law enforcers with headshots. Using Melee does not count towards this challenge!
ch_bronco_head_shots_4_hl = "TranslationHere",--Bronco .44 expert IV
ch_ak47_vs_the_law_1_hl = "TranslationHere",--AK VS. the Law I
ch_bronco_head_shots_1_hl = "TranslationHere",--Bronco .44 expert I
ch_glock_head_shots_2_hl = "TranslationHere",--STRYK VS. the Law Headshot II
ch_reinbeck_head_shots_1_hl = "TranslationHere",--Reinbeck 880 expert I
ch_dont_lose_face = "TranslationHere",--Beat all original heists on OVERKILL difficulty without anyone getting traded from custody. To complete this challenge, you will have to have played the heist from the start.
ch_mp5_vs_the_law_3_hl = "TranslationHere",--Compact-5 VS. the Law III
ch_m14_vs_the_law_4_hl = "TranslationHere",--M308 VS. the Law IV
ch_c45_vs_the_law_1_hl = "TranslationHere",--Crosskill .45 VS. the Law I
ch_ak47_vs_the_law = "TranslationHere",--Using the AK, defeat ##ak47_law_kill## Law enforcers. Using Melee does not count towards this challenge!
ch_slaughterhouse_overkill_no_trade_hl = "TranslationHere",--Slaughterhouse: Don't lose face
ch_aquire_money_3 = "TranslationHere",--Acquire $100,000,000 in cash.
ch_m14_taser_head_shot_1_hl = "TranslationHere",--M308 VS. Tasers
ch_ak47_vs_the_law_6_hl = "TranslationHere",--AK VS. the Law VI
ch_c45_fbi_kill_1_hl = "TranslationHere",--Crosskill .45 VS. the FBI
ch_hk21_vs_the_law_5_hl = "TranslationHere",--Brenner 21 VS. the Law V
ch_m4_spooc_head_shot_1_hl = "TranslationHere",--Amcar-4 VS. Cloakers
ch_hk21_vs_the_law_2_hl = "TranslationHere",--Brenner 21 VS. the Law II
ch_saviour = "TranslationHere",--On UNDERCOVER, place 20 planks by yourself on windows, vents or fences.
ch_bronco_vs_the_law_3_hl = "TranslationHere",--Bronco .44 VS. the Law III
ch_mp5_vs_the_law_4_hl = "TranslationHere",--Compact-5 VS. the Law IV
ch_mossberg_vs_the_law_4_hl = "TranslationHere",--Locomotive 12G VS. the Law IV
ch_reinbeck_vs_the_law = "TranslationHere",--Using the Reinbeck 880, defeat ##reinbeck_law_kill## Law enforcers. Using Melee does not count towards this challenge!
ch_m79_simultaneous_kills_2_hl = "TranslationHere",--GL40 Cluster Kill II
ch_hk21_vs_the_law_4_hl = "TranslationHere",--Brenner 21 VS. the Law IV
ch_drop_armored_car_hl = "TranslationHere",--But how?
ch_c45_vs_the_law_5_hl = "TranslationHere",--Crosskill .45 VS. the Law V
ch_bronco_vs_the_law = "TranslationHere",--Using the Bronco .44, defeat ##bronco_law_kill## Law enforcers. Using Melee does not count towards this challenge!
ch_tris_tripmine = "TranslationHere",--Defeat three Law enforcers with a single Trip Mine.
ch_kill_thugs = "TranslationHere",--In PANIC ROOM, kill all armed thugs in and around the apartment building within 60 seconds of you and your crew drawing your weapons. To complete this challenge, you will have to have played the heist from the start.
ch_me_vs_swat = "TranslationHere",--Defeat ##swat_kill## blue SWAT. Using Trip Mines or Melee does not count towards this challenge!
ch_m14_vs_the_law_6_hl = "TranslationHere",--M308 VS. the Law VI
ch_mac11_head_shots = "TranslationHere",--Using the Mark 11, defeat ##mac11_law_head_shot## Law enforcers with headshots. Using Melee does not count towards this challenge!
ch_mac11_head_shots_4_hl = "TranslationHere",--Mark 11 expert IV
ch_beretta92_vs_the_law_5_hl = "TranslationHere",--B9-S VS. the Law V
ch_diamond_heist_no_deaths_hl = "TranslationHere",--Diamond Heist: Like a pro
ch_apartment_no_deaths = "TranslationHere",--Complete Panic Room on hard difficulty without being taken into custody.
ch_aquire_money_1 = "TranslationHere",--Acquire $20,000,000 in cash.
ch_melee_4_hl = "TranslationHere",--Saving bullets IV
ch_fall_to_bleed_out_hl = "TranslationHere",--I've fallen - and I can't get up!
ch_beretta92_head_shots_1_hl = "TranslationHere",--B9-S expert I
ch_bridge_on_overkill = "TranslationHere",--Complete Green Bridge on OVERKILL difficulty.
ch_mp5_vs_the_law_6_hl = "TranslationHere",--Compact-5 VS. the Law VI
ch_bronco_vs_the_law_2_hl = "TranslationHere",--Bronco .44 VS. the Law II
ch_me_vs_the_law_2_hl = "TranslationHere",--Me VS. the Law II
ch_mossberg_cop_kill_1_hl = "TranslationHere",--Locomotive 12G VS. Cops
ch_tiedown_fbi = "TranslationHere",--Force ##tiedown_fbi## FBI agents to cuff themselves.
ch_bridge_no_deaths_hl = "TranslationHere",--Green Bridge: Like a pro
ch_mac11_vs_the_law_4_hl = "TranslationHere",--Mark 11 VS. the Law IV
ch_hk21_head_shots_2_hl = "TranslationHere",--Brenner 21 expert II
ch_tiedown_smep_hl = "TranslationHere",--Owning the HEAVY SWATS
ch_apartment_overkill_no_trade = "TranslationHere",--Complete Panic Room on OVERKILL difficulty without anyone getting traded from custody.
ch_tiedown_smep = "TranslationHere",--Force ##tiedown_smep## HEAVY SWATS to cuff themselves.
ch_windowlicker = "TranslationHere",--Defeat a law enforcer planting C4 in FIRST WORLD BANK on hard difficulty or above. To complete this challenge, you will have to have played the heist from the start.
ch_reinbeck_vs_the_law_5_hl = "TranslationHere",--Reinbeck 880 VS. the Law V
ch_mossberg_vs_the_law = "TranslationHere",--Using the Locomotive 12G, defeat ##mossberg_law_kill## Law enforcers. Using Melee does not count towards this challenge!
ch_c45_head_shots_4_hl = "TranslationHere",--Crosskill .45 expert IV
ch_beretta92_vs_the_law = "TranslationHere",--Using the B9-S, defeat ##beretta92_law_kill## Law enforcers. Using Melee does not count towards this challenge!
ch_bronco_head_shots = "TranslationHere",--Using the Bronco .44, defeat ##bronco_law_head_shot## Law enforcers with headshots. Using Melee does not count towards this challenge!
ch_bronco_tank_kill = "TranslationHere",--Using the Bronco .44, defeat ##bronco_tank_kill## bulldozers. Using Melee does not count towards this challenge!
ch_reinbeck_vs_the_law_3_hl = "TranslationHere",--Reinbeck 880 VS. the Law III
ch_mac11_head_shots_2_hl = "TranslationHere",--Mark 11 expert II
ch_m14_vs_the_law_5_hl = "TranslationHere",--M308 VS. the Law V
ch_hk21_shield_kill = "TranslationHere",--Using the Brenner 21, defeat ##hk21_shield_kill## Shields. Using Melee does not count towards this challenge!
ch_quad_tripmine_hl = "TranslationHere",--Four guys went on a Trip
ch_bleed_out_kill = "TranslationHere",--Defeat ##bleed_out_kill## Law enforcers while you're in bleedout. Using Trip Mines or Sentry Gun does not count towards this challenge!
ch_bleed_out_multikill = "TranslationHere",--Defeat ##bleed_out_multikill## Law enforcers during a single bleedout.
ch_revived_single = "TranslationHere",--Get revived by one of your crew mates.
ch_arrested_hl = "TranslationHere",--OK, you got me!
ch_tiedown_civilian = "TranslationHere",--Tie down ##tiedown_civilians## civilians.
ch_tiedown_cop = "TranslationHere",--Force ##tiedown_cop## Police officers to cuff themselves.
ch_tiedown_fbi_hl = "TranslationHere",--Owning the FBI
ch_deploy_ammobag = "TranslationHere",--Deploy ##deploy_ammobag## Ammo Bags.
ch_aquire_money_4 = "TranslationHere",--Acquire $200,000,000 in cash.
ch_aquire_money_6_hl = "TranslationHere",--...and that's a lot of cash VI
ch_bank_no_deaths_hl = "TranslationHere",--First World Bank: Like a pro
ch_bank_overkill_no_trade = "TranslationHere",--Complete First World Bank on OVERKILL difficulty without anyone getting traded from custody.
ch_street_no_civilians = "TranslationHere",--Complete Heat Street on hard difficulty without killing any civilians.
ch_street_no_deaths_hl = "TranslationHere",--Heat Street: Like a pro
ch_street_no_bleedouts = "TranslationHere",--Complete Heat Street on hard difficulty without going into bleedout.
ch_street_on_overkill_hl = "TranslationHere",--Heat Street: OVERKILL
ch_bridge_no_bleedouts = "TranslationHere",--Complete Green Bridge on hard difficulty without going into bleedout.
ch_apartment_no_bleedouts = "TranslationHere",--Complete Panic Room on hard difficulty without going into bleedout.
ch_slaughterhouse_no_deaths_hl = "TranslationHere",--Slaughterhouse: Like a pro
ch_slaughterhouse_no_bleedouts = "TranslationHere",--Complete Slaughterhouse on hard difficulty without going into bleedout.
ch_diamond_heist_no_bleedouts_hl = "TranslationHere",--Diamond Heist: Bulletproof
ch_akimbo_hl = "TranslationHere",--Akimbo
ch_left_for_dead = "TranslationHere",--Finish a heist in custody while all your team mates are alive. (4 teammates).
ch_blood_in_blood_out = "TranslationHere",--Trade all the butchers in SLAUGHTERHOUSE.
ch_drop_armored_car = "TranslationHere",--Get the armored car to drop without shooting at it in SLAUGHTERHOUSE. To complete this challenge, you will have to have played the heist from the start.
ch_take_money = "TranslationHere",--Find ten money bundles in PANIC ROOM.
ch_take_money_hl = "TranslationHere",--Are there more than two?
ch_chavez_can_run = "TranslationHere",--In PANIC ROOM, take the key from Chavez within the first 45 seconds of starting the mission. To complete this challenge, you will have to have played the heist from the start.
ch_quick_gold_hl = "TranslationHere",--Gold digger
ch_kill_thugs_hl = "TranslationHere",--Quick draw
ch_kill_cameras = "TranslationHere",--Destroy all the cameras in FIRST WORLD BANK within 10 seconds of drawing your weapons. To complete this challenge, you will have to have played the heist from the start.
ch_hot_lava = "TranslationHere",--Don't let any law enforcers reach the graffiti on the center of the roof in PANIC ROOM from the SECURE THE ROOF objective until the ESCAPE objective on hard or OVERKILL difficulty. To complete this challenge, you will have to have played the heist from the start.
ch_federal_crime = "TranslationHere",--Defeat 25 FBI agents in a row.
ch_federal_crime_hl = "TranslationHere",--Federal crime
ch_bomb_man = "TranslationHere",--In DIAMOND HEIST, defeat all twelve Patrol Guards using only trip mines. To complete this challenge, you will have to have played the heist from the start.
ch_duck_hunting = "TranslationHere",--Complete the GREEN BRIDGE on hard or OVERKILL difficulty. To complete this challenge, you will have to have played the heist from the start.
ch_ready_yet = "TranslationHere",--In DIAMOND HEIST, get Bain to come back for you at least 7 times on hard or OVERKILL difficulty. To complete this challenge, you will have to have played the heist from the start.
ch_citys_finest = "TranslationHere",--Defeat 44,150 law enforcers (2010 numbers.)
ch_dozen_angry = "TranslationHere",--In DIAMOND HEIST, get the big diamond and escape on OVERKILL difficulty with you and all your team mates alive. To complete this challenge, you will have to have played the heist from the start.
ch_noob_herder = "TranslationHere",--Beat any heist on OVERKILL difficulty with three other players who are all using the Noob Lube perk. To complete this challenge, you will have to have played the heist from the start.
ch_noob_herder_hl = "TranslationHere",--Noob herder
ch_got_your_back_hl = "TranslationHere",--Got your back, noob
ch_aint_afraid = "TranslationHere",--Gain a level in the Assault tree during an assault.
ch_aint_afraid_hl = "TranslationHere",--I ain't afraid no more
ch_crack_bang = "TranslationHere",--Gain a level in the Sharpshooter tree with your last kill being a Sniper.
ch_crack_bang_hl = "TranslationHere",--Crack-bang
ch_lay_on_hands = "TranslationHere",--Gain a level in the Support tree while reviving a teammate.
ch_lay_on_hands_hl = "TranslationHere",--Lay on hands
ch_overkill_hl = "TranslationHere",--OVERKILL
ch_glock_vs_the_law_2_hl = "TranslationHere",--STRYK VS. the Law II
ch_glock_vs_the_law_5_hl = "TranslationHere",--STRYK VS. the Law V
ch_glock_vs_the_law_6_hl = "TranslationHere",--STRYK VS. the Law VI
ch_glock_head_shots_3_hl = "TranslationHere",--STRYK VS. the Law Headshot III
ch_glock_shield_body_shot_1_hl = "TranslationHere",--STRYK VS. Shields
ch_ak47_vs_the_law_3_hl = "TranslationHere",--AK VS. the Law III
ch_ak47_head_shots_1_hl = "TranslationHere",--AK VS. the Law Headshot I
ch_ak47_head_shots_2_hl = "TranslationHere",--AK VS. the Law Headshot II
ch_ak47_head_shots_4_hl = "TranslationHere",--AK VS. the Law Headshot IV
ch_ak47_taser_kill_1_hl = "TranslationHere",--AK VS. Tasers
ch_m79_vs_the_law_3_hl = "TranslationHere",--GL40 VS. the Law III
ch_m79_vs_the_law_4_hl = "TranslationHere",--GL40 VS. the Law IV
ch_m79_vs_the_law_6_hl = "TranslationHere",--GL40 VS. the Law VI
ch_sentry_gun_vs_the_law_1_hl = "TranslationHere",--SENTRY GUN VS. the Law I
ch_sentry_gun_vs_the_law_3_hl = "TranslationHere",--SENTRY GUN VS. the Law III
ch_sentry_gun_vs_the_law_4_hl = "TranslationHere",--SENTRY GUN VS. the Law IV
ch_sentry_gun_vs_the_law_5_hl = "TranslationHere",--SENTRY GUN VS. the Law V
ch_sentry_gun_vs_the_law_6_hl = "TranslationHere",--SENTRY GUN VS. the Law VI
ch_sentry_gun_row_kills_2_hl = "TranslationHere",--SENTRY GUN Kills in a Row II
ch_sentry_gun_row_kills_3_hl = "TranslationHere",--SENTRY GUN Kills in a Row III
ch_sentry_gun_resources_hl = "TranslationHere",--SENTRY GUN VS. the World
ch_ak47_head_shots = "TranslationHere",--Using the AK, defeat ##ak47_law_head_shot## Law enforcers with headshots. Using Melee does not count towards this challenge!
ch_m79_head_shots = "TranslationHere",--Using the GL40, defeat ##m79_law_head_shot## Law enforcers with headshots. Using Melee does not count towards this challenge!
ch_glock_shield_body_shot = "TranslationHere",--Using the STRYK, defeat ##glock_shield_body_shot## Shields with bodyshots. Using Melee does not count towards this challenge!
ch_ak47_taser_kill = "TranslationHere",--Using the AK, defeat ##ak47_taser_kill## Tasers. Using Melee does not count towards this challenge!
ch_sentry_gun_vs_the_law = "TranslationHere",--Using the SENTRY GUN, defeat ##sentry_gun_law_kill## Law enforcers.
ch_sentry_gun_resources = "TranslationHere",--Be in a team that places four Sentry Guns during a heist.
ch_m79_simultaneous_specials = "TranslationHere",--Using the GL40, defeat ##m79_simultaneous_specials## Special Units simultaneously.
ch_secret_stash_overkill_no_trade = "TranslationHere",--Complete UNDERCOVER on OVERKILL difficulty without anyone getting traded from custody.
ch_secret_stash_overkill_no_trade_hl = "TranslationHere",--UNDERCOVER: Don't lose face
ch_secret_stash_on_overkill_145 = "TranslationHere",--Complete UNDERCOVER on OVERKILL 145+ difficulty.
ch_secret_stash_on_overkill_145_hl = "TranslationHere",--In for a Dime, In for a Dollar
ch_suburbia_no_civilians_hl = "TranslationHere",--COUNTERFEIT: Clean hit
ch_suburbia_no_civilians = "TranslationHere",--Complete COUNTERFEIT on hard difficulty without killing any civilians.
ch_suburbia_overkill_no_trade = "TranslationHere",--Complete COUNTERFEIT on OVERKILL difficulty without anyone getting traded from custody.
ch_suburbia_overkill_no_trade_hl = "TranslationHere",--COUNTERFEIT: Don't lose face
ch_suburbia_on_overkill_145_hl = "TranslationHere",--Under Pressure
ch_blow_out = "TranslationHere",--Beat UNDERCOVER with everyone in the crew only using the GL40. To complete this challenge, everyone in your crew will have to have played the heist from the start. Using Melee does not count towards this challenge!
ch_crowd_control_hl = "TranslationHere",--Crowd control
ch_det_gadget_hl = "TranslationHere",--Detective Gadget
ch_det_gadget = "TranslationHere",--Beat any heist using the STRYK Pistol, AK Rifle, GL40 Grenade Launcher, Toolkit upgrade, Sentry Gun equipment and Big Game Hunters crew bonus. To complete this challenge, you will have to have played the heist from the start.
ch_pacifist = "TranslationHere",--Beat COUNTERFEIT on hard difficulty or above without killing any law enforcers or civilians. To complete this challenge, everyone in your crew will have to have played the heist from the start.
ch_quick_hands_hl = "TranslationHere",--Quick hands
ch_quick_hands = "TranslationHere",--On COUNTERFEIT, manage to defuse all C4 charges.
ch_street_on_overkill_145_hl = "TranslationHere",--Hills Street Blues
ch_street_on_overkill_145 = "TranslationHere",--Beat HEAT STREET on OVERKILL 145+ difficulty. To complete this challenge, you will have to have played the heist from the start.
ch_apartment_on_overkill_145 = "TranslationHere",--Beat PANIC ROOM on OVERKILL 145+ difficulty. To complete this challenge, you will have to have played the heist from the start.
ch_slaughterhouse_on_overkill_145_hl = "TranslationHere",--Lots of pigs, but no pigs
ch_diamond_heist_on_overkill_145_hl = "TranslationHere",--Bad code
ch_diamond_heist_on_overkill_145 = "TranslationHere",--Beat DIAMOND HEIST on OVERKILL 145+ difficulty. To complete this challenge, you will have to have played the heist from the start.
ch_president_hl = "TranslationHere",--Four more years
ch_president = "TranslationHere",--Reach level 145. This gives you the presidential masks for further campaigning.
ch_christmas_present_hl = "TranslationHere",--Merry Xmas
ch_hos_dont_panic_hl = "TranslationHere",--Don't panic
ch_hos_dont_panic = "TranslationHere",--Complete NO MERCY on hard or OVERKILL without any civilian raising the alarm. To complete this challenge, you will have to have played the heist from the start.
ch_hos_cut_wire_hl = "TranslationHere",--...or was it the blue one?
ch_hos_wrong_door_hl = "TranslationHere",--That's the wrong door, again!
ch_hos_wrong_door = "TranslationHere",--Complete NO MERCY on OVERKILL difficulty, having sawed open all three ICU security doors. To complete this challenge, you will have to have played the heist from the start.
ch_hos_afraid_of_the_dark_hl = "TranslationHere",--Afraid of the dark
