debug_interact_bodybags_bag_take_bodybag = "TranslationHere",--Hold $BTN_INTERACT; to grab a body bag
debug_interact_grenade_crate_take_grenades = "TranslationHere",--Hold $BTN_INTERACT; to grab a throwable
debug_interact_hold_to_breach = "TranslationHere",--Hold $BTN_INTERACT; to Breach
debug_interact_hospital_sentry = "TranslationHere",--hold $BTN_INTERACT; to set up the sentry gun
debug_interact_hospital_phone = "TranslationHere",--Press $BTN_INTERACT; to answer the phone
debug_wskn_customize = "TranslationHere",--Debug Skin
debug_upgrade_tree_support = "TranslationHere",--SUPPORT
debug_interact_equipment_gold = "TranslationHere",--You need Gold!
debug_interact_free_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Rescue your Teammate
debug_interact_apartment_helicopter = "TranslationHere",--Hold $BTN_INTERACT; to Attach the Magnet
debug_give_alot_of_lootdrops = "TranslationHere",--Give alot of lootdrops (1000 of each payclass)
debug_give_alot_of_money = "TranslationHere",--Give money (10 completed jobs of each star)
debug_instruct_finish_arrest = "TranslationHere",--Press $BTN_INTERACT; to get up
debug_interact_cutter_jammed_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Restart the Cutter
debug_suburbia = "TranslationHere",--Counterfeit
debug_upgrade_new_equipment = "TranslationHere",--NEW EQUIPMENT
debug_interact_laptop_objective_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Erase security footage
debug_wskn_submit_no_screenshot = "TranslationHere",--No screenshot selected
debug_interact_equipment_requires_cable_ties = "TranslationHere",--You need cable ties
debug_modify_active_challenges = "TranslationHere",--Modify active challenges
debug_interact_trip_mine_PS3 = "TranslationHere",--Press $BTN_INTERACT; to Turn Trip Mine On or Off
debug_wskn_sure_to_delete = "TranslationHere",--Are you sure you want to delete this skin?
debug_interact_equipment_gas = "TranslationHere",--You need Gasoline
debug_interact_c4_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Place the Explosives
debug_wskn_cubemap_pattern_control_x = "TranslationHere",--Pattern Cubemap Intensity
debug_interact_copy_machine = "TranslationHere",--Press $BTN_INTERACT; to open the Copy Machine
debug_wskn_save_leg_kit = "TranslationHere",--Copy Special Kit to Clipboard
debug_interact_hack_ipad = "TranslationHere",--Hold $BTN_INTERACT; to set up Device
debug_show_marketplace_ui = "TranslationHere",--MARKETPLACE
debug_interact_gas_PS3 = "TranslationHere",--Press $BTN_INTERACT; to pour Gasoline
debug_ak47_short = "TranslationHere",--AK
debug_button_x = "TranslationHere",--$BTN_X;
debug_interact_computer_test_PS3 = "TranslationHere",--Press $BTN_INTERACT; to Copy the files
debug_interact_saw = "TranslationHere",--Hold $BTN_INTERACT; to Place the Saw
debug_interact_gold_pile_take_money = "TranslationHere",--Hold $BTN_INTERACT; to Take the Gold
debug_interact_trade_hostage_skm = "TranslationHere",--Hold $BTN_INTERACT; to Trade the Hostage
debug_wskn_pattern = "TranslationHere",--Pattern
debug_copy_weapon_customize = "TranslationHere",--Copy to Clipboard
debug_interact_requires_gold_bag = "TranslationHere",--Hold $BTN_INTERACT; to Drop the Bag
debug_equipment_blood_sample_valid = "TranslationHere",--VALID BLOOD SAMPLE
debug_interact_being_revived = "TranslationHere",--You are Being Helped Up
debug_interact_elevator_door_roof = "TranslationHere",--Press $BTN_INTERACT; to START the Elevator
debug_interact_equipment_stash_server = "TranslationHere",--You Need the Server
debug_interact_crowbar2 = "TranslationHere",--Hold $BTN_INTERACT; to Breach the Trunk
debug_mugshot_in_custody = "TranslationHere",--In custody.
debug_equipment_stash_planks = "TranslationHere",--PLANKS
debug_interact_stash_server_cord = "TranslationHere",--Press $BTN_INTERACT; to Connect the Power Cord
debug_interact_elevator_door = "TranslationHere",--Press $BTN_INTERACT; to Call the Elevator
debug_button_b = "TranslationHere",--$BTN_B;
debug_interact_diamond = "TranslationHere",--Press $BTN_INTERACT; to take the diamond
debug_button_y = "TranslationHere",--[G]
debug_wskn_uv_scale_lock = "TranslationHere",--Lock Scale
debug_interact_hack_ipad_jammed_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to reboot
debug_interact_gas = "TranslationHere",--Press $BTN_INTERACT; to pour Gasoline
debug_wskn_no_skin = "TranslationHere",--No skin
debug_wskn_color = "TranslationHere",--Color
debug_interact_diamond_PS3 = "TranslationHere",--Press $BTN_INTERACT; to take the diamond
debug_wskn_parts = "TranslationHere",--By Part
debug_sandbox_description = "TranslationHere",--Playground for the developers.
debug_interact_search_key = "TranslationHere",--Hold $BTN_INTERACT; to Search for Key
debug_doctor_bag = "TranslationHere",--Doctor Bag
debug_upgrade_crewbonus = "TranslationHere",--CREW BONUS
debug_instruct_mask_on_PS3 = "TranslationHere",--Press $BTN_INTERACT; to Start the Heist
debug_wskn_cyan = "TranslationHere",--Cyan
debug_wskn_pattern_tweak_z = "TranslationHere",--Pattern Spec Opacity
debug_interact_equipment_blood_sample_verified = "TranslationHere",--you need a valid blood sample
debug_interact_equipment_cable_tie = "TranslationHere",--You need cable ties
debug_mission_end_debug_continue_PS3 = "TranslationHere",--$BTN_Y; Debug continue
debug_wskn_base_skin = "TranslationHere",--Base Skin
debug_interact_requires_gold_bag_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Drop the Bag
debug_wskn_browse_skin = "TranslationHere",--Browse to skin folder
debug_interact_saw_jammed_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Restart the Saw
debug_interact_copy_machine_PS3 = "TranslationHere",--Press $BTN_INTERACT; to open the Copy Machine
debug_interact_drill_jammed = "TranslationHere",--Hold $BTN_INTERACT; to Restart the Drill
debug_start_the_game = "TranslationHere",--Debug Start
debug_interact_security_station_jammed = "TranslationHere",--Hold $BTN_INTERACT; to Continue
debug_wskn_pattern_tweak_y = "TranslationHere",--Pattern Rotation
debug_interact_drill = "TranslationHere",--Hold $BTN_INTERACT; to Place the Drill
debug_heist_failed = "TranslationHere",--HEIST FAILED!
debug_c4_diffusible = "TranslationHere",--Hold $BTN_INTERACT; to Defuse the C4
debug_exp_exp_suffix = "TranslationHere",--K
debug_interact_revive = "TranslationHere",--Hold $BTN_INTERACT; to Help your Teammate Up
debug_interact_search_key_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Search for Key
debug_interact_equipment_stash_planks = "TranslationHere",--You need some Planks
debug_interact_intimidate_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Tie Hands
debug_wskn_changelog_input = "TranslationHere",--Changelog
debug_wskn_pattern_tweak_x = "TranslationHere",--Pattern Scale
debug_toolset = "TranslationHere",--Toolkit
debug_equipment_stash_server = "TranslationHere",--SERVER
debug_interact_being_freed = "TranslationHere",--You are Being Rescued
debug_wskn_save_skin_local = "TranslationHere",--Save skin
debug_instruct_mask_on = "TranslationHere",--Press $BTN_INTERACT; to start the Heist
debug_upgrade_tree_technician = "TranslationHere",--TECHNICIAN
debug_interact_drill_jammed_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Restart the Drill
debug_interact_hospital_security_cable = "TranslationHere",--hold $BTN_INTERACT; to cut the cable
debug_interact_hostage_stay = "TranslationHere",--Hold $BTN_INTERACT; to sit the hostage down
debug_wskn_new_skin = "TranslationHere",--New skin
debug_interact_hospital_veil_container = "TranslationHere",--hold $BTN_INTERACT; to stash the Vial
debug_wskn_bonus = "TranslationHere",--Bonus
debug_interact_money_wrap_take_money = "TranslationHere",--Hold $BTN_INTERACT; to Fill the Money bag
debug_interact_apartment_helicopter_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Attach the Magnet
debug_wskn_title_input = "TranslationHere",--Title
debug_wskn_pink = "TranslationHere",--Pink
debug_button_upgrade_alt4 = "TranslationHere",--[4]
debug_interact_printing_plates = "TranslationHere",--Hold $BTN_INTERACT; to Take the Printing Plate
debug_equipment_first_aid_kit = "TranslationHere",--First Aid Kit
debug_interact_gold_pile_take_money_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Take the Gold
debug_sandbox = "TranslationHere",--Sandbox
debug_interact_sewer_manhole = "TranslationHere",--Hold $BTN_INTERACT; to Open the Manhole
debug_interact_tear_painting = "TranslationHere",--Press $BTN_INTERACT; to Tear the Painting
debug_interact_diamond_case = "TranslationHere",--Press $BTN_INTERACT; to open
debug_freeflight = "TranslationHere",--Freeflight
debug_interact_laptop_objective = "TranslationHere",--Hold $BTN_INTERACT; to Erase security footage
debug_interact_interaction_ball = "TranslationHere",--Hold $BTN_INTERACT; to Pull the Hose
debug_mission_gameover_exit_PS3 = "TranslationHere",--$BTN_A; Exit
debug_wskn_uv_scale_z = "TranslationHere",--Sticker Quality Influence
debug_upgrade_new_weapon = "TranslationHere",--NEW WEAPON
debug_interact_crowbar_breach = "TranslationHere",--Hold $BTN_INTERACT; to Breach
debug_interact_computer_test = "TranslationHere",--Press $BTN_INTERACT; to copy the files
debug_interact_stash_planks = "TranslationHere",--Hold $BTN_INTERACT; to Barricade
debug_interact_revive_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Help your Teammate Up
debug_wskn_pattern_gradient = "TranslationHere",--Pattern Gradient
debug_interact_free = "TranslationHere",--Hold $BTN_INTERACT; to Rescue your Teammate
debug_interact_embassy_door_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Open The Door
debug_interact_temp_interact_box_press = "TranslationHere",--Press $BTN_INTERACT; to interact
debug_exp_level_progression = "TranslationHere",--REPUTATION PROGRESSION:
debug_lu_menu_help = "TranslationHere",--HOLD [TAB] TO CHANGE SPECIALTY
debug_interact_money_printed_take_money = "TranslationHere",--Hold $BTN_INTERACT; to take the Money
debug_post_effects = "TranslationHere",--Post Effects
debug_interact_equipment_key = "TranslationHere",--Take the Bank Manager Key to get to the Drill
debug_interact_numpad = "TranslationHere",--Press $BTN_INTERACT; to enter the code
debug_equipment_ecm_jammer = "TranslationHere",--ECM jammer
debug_interact_apartment_key = "TranslationHere",--Press $BTN_INTERACT; to use the Key
debug_interact_hospital_saw_teddy = "TranslationHere",--Hold $BTN_INTERACT; to Pick up the saw
debug_interact_circuit_breaker = "TranslationHere",--Press $BTN_INTERACT; to Turn on the Power
debug_interact_take_christmas_present = "TranslationHere",--Press $BTN_INTERACT; to Take the Xmas Present
debug_upgrade_tree_sharpshooter = "TranslationHere",--SHARPSHOOTER
debug_lu_next_level = "TranslationHere",--NEXT UPGRADE
debug_mission_end_continue = "TranslationHere",--$CONTINUE; Continue to lobby
debug_ak47 = "TranslationHere",--AK rifle
debug_interact_open_trunk = "TranslationHere",--Hold $BTN_INTERACT; to Open Trunk
debug_exp_exp = "TranslationHere",--CASH:
debug_interact_c4 = "TranslationHere",--Hold $BTN_INTERACT; to Place the Explosives
debug_interact_money_wrap_single_bundle_take_money_PS3 = "TranslationHere",--Press $BTN_INTERACT; to Take the Money
debug_equipment_gas = "TranslationHere",--Gasoline
debug_corrupt_save = "TranslationHere",--[Corrupt Save File]
debug_button_y_PS3 = "TranslationHere",--$BTN_USE_ITEM;
debug_interact_crowbar = "TranslationHere",--Hold $BTN_INTERACT; to Breach the Door
debug_interact_c4_bag = "TranslationHere",--Hold $BTN_INTERACT; to Pick up Explosives
debug_interact_equipment_thermite = "TranslationHere",--You need Thermite!
debug_exp_level = "TranslationHere",--REPUTATION
debug_button_upgrade_alt4_PS3 = "TranslationHere",--$BTN_X;
debug_glock_short = "TranslationHere",--STRYK
debug_interact_open_door = "TranslationHere",--Hold $BTN_INTERACT; to Open The Door
debug_chat_say = "TranslationHere",--Chat:
debug_equipment_blood_sample = "TranslationHere",--BLOOD SAMPLE
debug_interact_equipment_money_bag = "TranslationHere",--Someone else needs to take this Money
debug_interact_cutter_jammed = "TranslationHere",--Hold $BTN_INTERACT; to Restart the Cutter
debug_interact_money_wrap_take_money_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Fill the Money bag
debug_ammo_bag = "TranslationHere",--Ammo Bag
debug_buttons = "TranslationHere",--Buttons: $BTN_A; $BTN_B; $BTN_X; $BTN_Y; $BTN_STICK_R;
debug_interact_ammo_bag_take_ammo_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Take Ammo
debug_interact_embassy_door = "TranslationHere",--Hold $BTN_INTERACT; to Open The Door
debug_interact_equipment_c4 = "TranslationHere",--Requires C4
debug_interact_equipment_crowbar = "TranslationHere",--You Need a Crowbar
debug_interact_equipment_requires_gold_bag = "TranslationHere",--You need gold
debug_interact_equipment_saw = "TranslationHere",--Get the Saw
debug_interact_equiptment_apartment_key = "TranslationHere",--Take the key from Chavez
debug_interact_equiptment_sample_validation = "TranslationHere",--Requires a Blood Sample
debug_interact_gage_assignment_take = "TranslationHere",--Hold $BTN_INTERACT; to pick up the package
debug_interact_gen_pku_loot_take = "TranslationHere",--Press $BTN_INTERACT; to Take the loot
debug_interact_intimidate = "TranslationHere",--Hold $BTN_INTERACT; to Tie Hands
debug_interact_key = "TranslationHere",--Press $BTN_INTERACT; to use the Keycard
debug_interact_key_PS3 = "TranslationHere",--Press $BTN_INTERACT; to use the Keycard
debug_interact_money_wrap_single_bundle_take_money = "TranslationHere",--Press $BTN_INTERACT; to Take the Money
debug_interact_move_bookshelf = "TranslationHere",--Hold $BTN_INTERACT; to Move the Bookshelf
debug_interact_numpad_PS3 = "TranslationHere",--Press $BTN_INTERACT; to enter the code
debug_interact_saw_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Place the Saw
debug_interact_stash_planks_pickup = "TranslationHere",--Hold $BTN_INTERACT; to Take the Planks
debug_interact_stash_server = "TranslationHere",--Hold $BTN_INTERACT; to Connect the Server
debug_interact_stash_server_pickup = "TranslationHere",--Hold $BTN_INTERACT; to Take the Server
debug_interact_temp_interact_box = "TranslationHere",--Hold $BTN_INTERACT; to interact
debug_interact_temp_interact_box_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to interact
debug_interact_thermite_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to place the Thermite
debug_interact_trade = "TranslationHere",--Hold $BTN_INTERACT; to Trade your Teammate
debug_interact_trade_PS3 = "TranslationHere",--Hold $BTN_INTERACT; to Trade your Teammate
debug_interact_transformer_box = "TranslationHere",--Hold $BTN_INTERACT; to Turn on the Power
debug_interact_trip_mine = "TranslationHere",--Press $BTN_INTERACT; to Turn Trip Mine On or Off
debug_interact_water_tap = "TranslationHere",--Hold $BTN_INTERACT; to Turn on the Water
debug_loading_level = "TranslationHere",--Loading
debug_lu_current_spec = "TranslationHere",--CURRENT SPEC:
debug_lu_level_locked = "TranslationHere",--LOCKED TO REPUTATION
debug_lu_menu_help_PS3 = "TranslationHere",--HOLD $BTN_BACK; TO CHANGE SPECIALTY
debug_lu_unlocked = "TranslationHere",--UNLOCKED
debug_m79_short = "TranslationHere",--GL40
debug_mission_end_continue_PS3 = "TranslationHere",--$BTN_A; Continue to lobby
debug_mission_end_debug_continue = "TranslationHere",--[g] Debug continue
debug_mission_gameover_exit = "TranslationHere",--[ENTER] Exit
debug_modify_active_challenges_help = "TranslationHere",--List all counter based active challenges. Selecting one will result in that challenges only having one left before completion. Select will also force an update off the menu.
debug_mugshot_cuffed = "TranslationHere",--Cuffed
debug_mugshot_downed = "TranslationHere",--Downed
debug_mugshot_electrified = "TranslationHere",--Electrified
debug_next_stage = "TranslationHere",--Next stage
debug_next_upgrade = "TranslationHere",--NEXT UPGRADE:
debug_qatest = "TranslationHere",--QA test in roaming map
debug_secret_stash = "TranslationHere",--Undercover
debug_secret_stash_briefing = "TranslationHere",--The Taxman thought he was clever making a deal with a big corporation, but the information leaked, and now bigger sharks want in - all in. We have a complete, run-down building to ourselves, overlooking the deal. We've got a set-up installed. Alex will help with the crane. Scare the taxman into his limo, shake him up, and he'll be sure to give us the server and the codes. When it's about $25 million dollars, anything goes.
debug_sentry_gun = "TranslationHere",--Sentry Gun
debug_server_left = "TranslationHere",--HOST LEFT!
debug_silent_sentry_gun = "TranslationHere",--Suppressed Sentry Gun
debug_team_mate_need_free = "TranslationHere",--Teammate is under Arrest!
debug_toggle_mission_fading_debug_enabled = "TranslationHere",--Disable mission debug text
debug_trip_mine = "TranslationHere",--Trip Mine
debug_undecided = "TranslationHere",--Undecided
debug_upgrade_tree_assault = "TranslationHere",--ASSAULT
debug_wskn_base_gradient = "TranslationHere",--Base Gradient
debug_wskn_blue = "TranslationHere",--Blue
debug_wskn_blueprint = "TranslationHere",--Default Blueprint
debug_wskn_clear_skin = "TranslationHere",--Clear Skin
debug_wskn_cubemap_pattern_control_y = "TranslationHere",--Pattern Cubemap Influence
debug_wskn_delete_skin = "TranslationHere",--Delete skin
debug_wskn_desc_input = "TranslationHere",--Description
debug_wskn_edit_skin = "TranslationHere",--Edit Skin
debug_wskn_green = "TranslationHere",--Green
debug_wskn_name_input = "TranslationHere",--Enter ID here
debug_wskn_pattern_pos_x = "TranslationHere",--Pattern Position X
debug_wskn_pattern_pos_y = "TranslationHere",--Pattern Position Y
debug_wskn_publish_skin = "TranslationHere",--Publish
debug_wskn_rarity = "TranslationHere",--Rarity
debug_wskn_red = "TranslationHere",--Red
debug_wskn_save_kit = "TranslationHere",--Copy Kit to Clipboard
debug_wskn_save_skin = "TranslationHere",--Copy Skin to Clipboard
debug_wskn_sticker = "TranslationHere",--Sticker
debug_wskn_submit_failed = "TranslationHere",--Failed to submit skin
debug_wskn_take_screenshot = "TranslationHere",--Screenshot
debug_wskn_tbf_input = "TranslationHere",--Enter GUI Folder here
debug_wskn_types = "TranslationHere",--By Type
debug_wskn_uv_offset_rot_x = "TranslationHere",--Sticker X
debug_wskn_uv_offset_rot_z = "TranslationHere",--Sticker Rotation
debug_wskn_uv_scale_y = "TranslationHere",--Sticker Height
debug_wskn_white = "TranslationHere",--White
debug_wskn_yellow = "TranslationHere",--Yellow
wp_uc_power_back_up = "TranslationHere",--Get the Power Back Up!
wp_uc_saw_limo = "TranslationHere",--Use the Saw to Open the Limo!
