savefile_progress_description = "TranslationHere",--Player statistics and game progression.
savefile_game_title = "TranslationHere",--PAYDAY 2
savefile_autosave = "TranslationHere",--$TEXT_WITH_DATE; - AUTO SAVE
savefile_removing = "TranslationHere",--Removing...
savefile_loading = "TranslationHere",--Loading...
savefile = "TranslationHere",--$TEXT; - $DATE;
savefile_empty = "TranslationHere",--[New Save File]
savefile_setting_description = "TranslationHere",--User specific game settings.
savefile_progress = "TranslationHere",--Player progression: Version $VERSION; or higher is required.
savefile_setting = "TranslationHere",--Game settings: Version $VERSION; or higher is required.
savefile_saving = "TranslationHere",--Saving...
