wp_xsub_watervalve = "TranslationHere",--Open the Valve
wp_uc_computer = "TranslationHere",--Continue Hack
wp_xsub_waterhose = "TranslationHere",--Pull the Hose
wp_xsub_safe = "TranslationHere",--Investigate the Safe
wp_xsub_door = "TranslationHere",--Open the Door
wp_ap_escape = "TranslationHere",--Escape!
wp_xsub_hack = "TranslationHere",--Override the System
wp_xsub_shelter = "TranslationHere",--Get to the Shelter
wp_xsub_sewer = "TranslationHere",--Sewer
wp_uc_saw = "TranslationHere",--Saw the Limo
wp_xsub_tnt = "TranslationHere",--Place the Charge
wp_xsub_watertap = "TranslationHere",--Open the Tap
wp_xsub_outlet = "TranslationHere",--Plug into Power Outlet
wp_xsub_bbq = "TranslationHere",--Talk to Mitchell
wp_bridge_escape = "TranslationHere",--Escape!
wp_xsub_escape = "TranslationHere",--Escape!
wp_bank_escape = "TranslationHere",--Escape!
wp_xsub_power = "TranslationHere",--Turn on the Power
wp_uc_check_limo = "TranslationHere",--Check the Limo
wp_uc_escape = "TranslationHere",--Escape!
wp_uc_power = "TranslationHere",--Get the Power Back On
wp_uc_interogate = "TranslationHere",--Get the Code Words
wp_uc_keyboard = "TranslationHere",--Use the Keyboard
wp_str_esc = "TranslationHere",--Escape!
wp_slaughterhouse_escape = "TranslationHere",--Escape!
