dialog_cheated_host = "TranslationHere",--Couldn't play on an cheated server.
dialog_new_unlock_title = "TranslationHere",--Congratulations!
dialog_ask_save_progress_backup = "TranslationHere",--Save progress backup?
dialog_the_host_has_left_the_game = "TranslationHere",--The host has left the game
dialog_information_title = "TranslationHere",--Information
dialog_dropin_title = "TranslationHere",--$USER; is joining the game
dialog_mp_groupinvite_message = "TranslationHere",--Do you wish to join $GROUP;?
dialog_new_patch = "TranslationHere",--An update is needed to access online features.
dialog_transaction_successful = "TranslationHere",--TRANSACTION SUCCESSFUL
dialog_fail_load_dlc_corrupt = "TranslationHere",--Corrupted downloadable content detected. Please go to the Memory section of the Dashboard, delete the corrupted content and download it again.
dialog_error_title = "TranslationHere",--Error
dialog_mp_send_invite_message = "TranslationHere",--Do you wish to send a game invite to $FRIEND;?
dialog_err_not_signed_in_PS3 = "TranslationHere",--You must sign in to "PlayStation Network" to make use of network modes.
dialog_npcommerce_checkout_fail = "TranslationHere",--Checkout failed
dialog_blackmarket_lost_mods_warning = "TranslationHere",--(Your removed modifications will be placed in the inventory)
screen_autosaving_warning_PS3 = "TranslationHere",--This game saves data automatically at certain points.$NL;Please don't turn off your PlayStation®4 system when the following icon is displayed:
dialog_cs_claim_rewards = "TranslationHere",--Claim Rewards
dialog_cant_continue_cs_title = "TranslationHere",--This can not Continue
dialog_blackmarket_slot_item = "TranslationHere",--[SLOT $slot;] $item;
dialog_safehouse_text = "TranslationHere",--You haven't visited the safe house yet. Would you like to go there now?
dialog_blackmarket_buy_mask_slot = "TranslationHere",--Buying this will unlock one more mask slot.$NL;$NL;This will cost you $money;.
dialog_err_failed_creating_lobby = "TranslationHere",--Failed to create game.
dialog_err_room_is_full = "TranslationHere",--This room has been filled, please try another one.
dialog_return_to_cs_lobby = "TranslationHere",--Are you sure you want to return to the Crime Spree lobby?
dialog_no = "TranslationHere",--No
dialog_mp_vote_kick_message = "TranslationHere",--A vote has been initiated to kick $name; from the game. The vote will end in $time; seconds.
sm_moving_up_desc = "TranslationHere",--OK, I told you before that people are watching you, One guy in particular has an interest in you. I might have something big coming up with this new contact, but the job he has in mind will be difficult and you have to get ready for it. Come back when you've prepped a bit more and I will set you up.
dialog_unlock_skill_switch_free = "TranslationHere",--This one is free of charge.
dialog_cs_claim_rewards_text = "TranslationHere",--Are you sure you want to claim your Crime Spree rewards?$NL;$NL;This will end your current Crime Spree lobby, and you will have to start a new one to gain rewards again.
dialog_blackmarket_mod_conflict = "TranslationHere",--These modifications are not compatible and will be removed:$mods;
dialog_blackmarket_finalize_item = "TranslationHere",--$ITEM;$NL; You are about to finalize your customizations, this process is irreversible and will cost you $money;.
dialog_dlc_require_restart = "TranslationHere",--Attention
dialog_fail_load_progress_corrupt = "TranslationHere",--Progress corrupt. Data will now be deleted.
dialog_game_is_installing_menu = "TranslationHere",--This portion of the title has not been installed yet. Please try again when installation is complete.
dialog_too_low_level_ovk145 = "TranslationHere",--OVERKILL 145+ cannot be played with people below reputation level 145.
dialog_mp_kick_player_message = "TranslationHere",--Player $PLAYER; will be kicked from this game. Do you wish to continue?
dialog_cant_continue_cs_text = "TranslationHere",--You can not continue your Crime Spree as you do not have enough Continental Coins. In order to continue from $level;$BTN_SPREE_TICKET; you need $cost; Continental Coins.
dialog_connection_to_host_lost = "TranslationHere",--Connection to the host has been lost
dialog_skills_reseted_title = "TranslationHere",--Please note
dialog_abort_mission_text = "TranslationHere",--Are you sure you would like to terminate the current contract?$NL;$NL;You and your crew will be returned to the planning phase where a new contract can be selected.
ps4_presence_Idle = "TranslationHere",--In the menus
dialog_dlc_require_restart_desc = "TranslationHere",--You need to restart PAYDAY 2 to access your new items.
dialog_cs_crash_fail_text = "TranslationHere",--Your Crime Spree has failed due to an unexpected closure of the game.$NL;You can still pay the Continental Coin cost to continue.
dialog_mp_pending_invite_message = "TranslationHere",--YOU HAVE A PENDING GAME INVITE. SIGN IN TO "PlayStation Network" USING THE 'PLAY ONLINE' OPTION IN THE MAIN MENU TO JOIN THE GAME.
dialog_bm_mask_custom_final_title = "TranslationHere",--Are you sure?
dialog_skills_place_title = "TranslationHere",--Are you sure?
dialog_are_you_sure_you_want_stop_cs = "TranslationHere",--Are you sure you want to stop your Crime Spree?$NL;$NL;This will end your current Crime Spree, and no rewards will be given to you.
dialog_xp_to_specialization = "TranslationHere",--XP to Perk Conversion
dialog_connect_controller_text_X360 = "TranslationHere",--Please reconnect the Xbox One Wireless Controller and press $BTN_A;.
dialog_mp_kicked_out_title = "TranslationHere",--Kicked out
dialog_mp_invite_wrong_version_message = "TranslationHere",--The game you have been invited to is running another version of PAYDAY 2. You are unable to join.
dialog_blackmarket_mod_cost = "TranslationHere",--This will cost you $money;.
dialog_err_wrong_version_message = "TranslationHere",--The game you are trying to join is running another version of PAYDAY 2. You are unable to join.
dialog_key_binding_collision = "TranslationHere",--Key "$KEY;" is already mapped to "$MAPPED;", please remap it first.
dialog_accept = "TranslationHere",--Accept
dialog_blackmarket_buy_item = "TranslationHere",--Do you really want to buy $item;?$NL;$NL;It will cost you $money;.$NL;$NL;$num_in_inventory;
dialog_show_restart_game_message = "TranslationHere",--Are you sure you want to restart current game?
dialog_inactive_user_accepted_invite = "TranslationHere",--An invitation has been accepted by an inactive user. The invitation is successfully completed after pressing START.
dialog_blackmarket_mask_sell_mod_readded = "TranslationHere",--$mod; will return to your inventory.
dialog_new_unlock_weapon_mods = "TranslationHere",--You just got your first weapon modification. You can access the weapon modification screen by selecting a bought weapon and choosing MODIFY WEAPON from the menu.$NL;Follow the exclamation marks on your bought weapons to find your latest drops.
dialog_are_you_sure_you_want_leave = "TranslationHere",--Are you sure you want to leave this lobby?
dialog_unlock_skill_switch = "TranslationHere",--You are about to unlock a new skill set.$NL;$NL;$cost_text;
dialog_fail_load_progress_wrong_version_WIN32 = "TranslationHere",--Progress file wrong version. Data will now be deleted.
dialog_game_permission_changed = "TranslationHere",--The game settings have changed, you no longer have permission to join
dialog_err_failed_joining_lobby = "TranslationHere",--Failed joining game.
dialog_on_server_left_message_cs = "TranslationHere",--$message;$NL;Your Crime Spree is still active, but your rank has not changed.$NL;$NL;You will now be returned to the main menu.
dialog_mp_vote_kick_response_title = "TranslationHere",--Vote Kick
dialog_new_unlock_textures = "TranslationHere",--You just got your first pattern for mask customization.$NL;To customize a mask you will need a material, pattern and a pair of colors.
dialog_mp_vote_restart_response_title = "TranslationHere",--Vote Restart
dialog_fail_load_progress_wrong_version_retry = "TranslationHere",--Progress file wrong version. Version $VERSION; or higher is required. Try loading again?
dialog_blackmarket_slot_mask_remove_suffix = "TranslationHere",--Customizations will be sold for $money;.
dialog_vote_kick_no = "TranslationHere",--Don't Kick
dialog_connect_controller_title = "TranslationHere",--No Wireless Controller
dialog_unlock_skill_switch_spending_offshore = "TranslationHere",--It will cost you $spending; spending cash and $offshore; offshore cash.
dialog_signin_change_title_X360 = "TranslationHere",--Sign-in change
dialog_authentication_host_fail = "TranslationHere",--Steam could not authenticate Steam ID for the host.
dialog_npcommerce_empty_store = "TranslationHere",--There is no content available for download at this time. Please try again later.
dialog_continue_cs_title = "TranslationHere",--Continue Crime Spree
dialog_are_you_sure_you_want_stop_cs_refund = "TranslationHere",--Are you sure you want to stop your Crime Spree?$NL;$NL;This will end your current spree, and no rewards will be given to you. Your initial investment of $coins; Continental Coins will be returned to you.
dialog_blackmarket_item = "TranslationHere",--$item;
dialog_gage_assignment_completed_title = "TranslationHere",--YOU HAVE A NEW MESSAGE
dialog_connect_controller_text_WIN32 = "TranslationHere",--Please insert controller.
dialog_internet_connection_required = "TranslationHere",--A network connection is needed to access the online portions of this title.
legal_text = "TranslationHere",--PAYDAY 2 © 2019 Starbreeze AB. All rights reserved.  PAYDAY 2, PAYDAY, Starbreeze, Starbreeze Studios, and the Starbreeze logo are trademarks or registered trademarks of Starbreeze AB in Sweden and/or other countries. Published by 505 Games. 505 Games and the 505 Games logo are registered trademarks of 505 Games S.r.l. All other trademarks are the property of their respective owners.
dialog_load_wrong_user_WIN32 = "TranslationHere",--Save data belongs to a different user. No progress will be loaded.
dialog_does_not_own_heist = "TranslationHere",--You do not own this heist and are unable to join this server.
dialog_new_unlock_armors = "TranslationHere",--Your first armor upgrade has been unlocked. You can change your armor from both Inventory and Job Overview.
dialog_skilltree_reseted = "TranslationHere",--Changes have been made to the skill tree.$NL;$NL;All your skills have been reset and your skill points as well as your cash has been refunded.
dialog_new_unlock_masks = "TranslationHere",--You just got your first mask. All masks dropped will be placed in your stash. They can then be moved to an empty mask slot from where you can wear them and also customize if you got all the components for it.
dialog_new_unlock_colors = "TranslationHere",--You just got your first pair of colors for mask customization.$NL;To customize a mask you will need a material, pattern and a pair of colors.
dialog_the_host_has_left_the_game_cs = "TranslationHere",--The host has left the game. Your Crime Spree is still active, but your level has not changed.$NL;$NL;You will now be returned to the main menu.
dialog_ask_load_progress_backup_corrupt = "TranslationHere",--Progress profile corrupt. Load from Backup? Chosing NO will delete your progress.
dialog_npcommerce_browse_fail = "TranslationHere",--COULD NOT OPEN PlayStation®Store
dialog_new_unlock_secondaries = "TranslationHere",--$value; has been unlocked and can be purchased into one of your empty secondary weapon slots.
dialog_skills_respec_title = "TranslationHere",--Are you sure?
dialog_demo_info_title = "TranslationHere",--Welcome to the demo of PAYDAY 2!
dialog_respec_skilltree = "TranslationHere",--You are about to respec this skill tree.$NL;$NL;Doing a respec resets all skill points in the $tree; skill tree.
dialog_are_you_sure_you_want_to_leave_game_crime_spree = "TranslationHere",--Are you sure you want to leave current game?$NL;$NL;This will cause your current Crime Spree to fail, and you must pay to continue, or claim your rewards from a Crime Spree lobby.
dialog_mp_invite_title = "TranslationHere",--PAYDAY 2
dialog_parental_control = "TranslationHere",--Online service is disabled on your Sony Entertainment Network account due to parental control restrictions.
dialog_npcommerce_need_install = "TranslationHere",--To play the full version, you will need to restart the game after the installation is completed.
dialog_cs_ga_in_progress_text = "TranslationHere",--Gage Boosts can not be purchased after the mission has been started.
dialog_getting_world_list = "TranslationHere",--Getting world list
dialog_mp_pending_invite_short_message = "TranslationHere",--YOU HAVE A PENDING GAME INVITE.
dialog_vote_kick_yes = "TranslationHere",--Kick
dialog_mp_vote_restart_message = "TranslationHere",--A vote has been initiated to restart. The vote will end in $time; seconds.
dialog_err_not_signed_in_X360 = "TranslationHere",--You are not signed into Xbox Live, or you do not have the correct permissions to access Xbox Live functionality.
dialog_age_restriction = "TranslationHere",--Online service is disabled on your Sony Entertainment Network account due to parental control restrictions.
screen_autosaving_warning_WIN32 = "TranslationHere",--This game saves data automatically at certain points.$NL;Please don't turn off the game when it is saving.
dialog_safehouse_goto_text = "TranslationHere",--Do you want to go to your safe house?
dialog_blackmarket_buy_weapon_slot = "TranslationHere",--Buying this will unlock one more weapon slot.$NL;$NL;This will cost you $money;.
dialog_fail_load_setting_corrupt_retry = "TranslationHere",--Settings file corrupt. Try loading again?
dialog_mp_invite_message = "TranslationHere",--Please Join my PAYDAY 2 Game
dialog_too_low_level = "TranslationHere",--Your reputation is too low to join this server.
dialog_signin_question_X360 = "TranslationHere",--In order to save, you must be signed into a profile. Do you want to sign in now?
dialog_buy_weapon_message = "TranslationHere",--Do you want to buy weapon "$WEAPON;" for $COST;?
ps4_presence_SPPlaying = "TranslationHere",--Playing single player heist
dialog_ask_load_progress_backup_low_lvl = "TranslationHere",--Your local backup save is more recent than the last Steam save.$NL;$NL;Press YES if you want to load your local backup save.
dialog_new_unlock_materials = "TranslationHere",--You just got your first material for mask customization.$NL;To customize a mask you will need a material, pattern and a pair of colors.
dialog_warning_title = "TranslationHere",--Warning
dialog_ok = "TranslationHere",--Ok
dialog_allocate_skillpoint = "TranslationHere",--This will unlock the $skill; skill.$NL;$NL;It will cost $cost; and $points; out of $remaining_points; points.
dialog_bm_weapon_buy_title = "TranslationHere",--Are you sure?
dialog_leaving_lobby_title = "TranslationHere",--Leaving game
dialog_accept_changes = "TranslationHere",--Do you wish to keep these display settings? They will be reverted in $TIME;.
dialog_key_binding_forbidden = "TranslationHere",--Key "$KEY;" is reserved by the game, please try something else.
dialog_unlock_infamyitem = "TranslationHere",--You are about to unlock $item; item.$NL;$NL;It will cost $points; out of $remaining_points; points.
dialog_blackmarket_slot_mask_remove = "TranslationHere",--Return this mask back to your stash? $suffix;
dialog_join_pd2_clan = "TranslationHere",--Go to PAYDAY 2 community page
dialog_are_you_sure_you_want_leave_cs = "TranslationHere",--Are you sure you want to leave this lobby?$NL;$NL;Your Crime Spree will be suspended until you continue it.
dialog_fail_load_progress_wrong_version = "TranslationHere",--Progress file wrong version. Version $VERSION; or higher is required. Data will now be deleted.
dialog_cs_ga_already_purchased = "TranslationHere",--Already Purchased
dialog_cs_ga_already_purchased_text = "TranslationHere",--You can only purchase one Gage Boost per Crime Spree mission.
dialog_challenge_warn_choose_reward_title = "TranslationHere",--Are you sure?
dialog_mp_disconnected_internet_X360 = "TranslationHere",--You have been disconnected from Xbox Live. You must be connected to access the online portions of this title.
dialog_fail_load_setting_wrong_version_WIN32 = "TranslationHere",--Settings file wrong version. Data will now be deleted.
dialog_does_not_own_heist_info = "TranslationHere",--Heist "$HEIST;" cannot be played with player $PLAYER;.
dialog_storage_removed_warning_X360 = "TranslationHere",--Selected storage device has been removed. Your progress will no longer be saved
dialog_wait_title = "TranslationHere",--Please wait
dialog_cs_ga_in_progress = "TranslationHere",--Heist In Progress
dialog_creating_lobby_title = "TranslationHere",--Creating game
dialog_bm_mask_assemble_title = "TranslationHere",--Are you sure?
dialog_mp_send_invite_title = "TranslationHere",--Send game invite
dialog_apply = "TranslationHere",--Apply
dialog_connect_controller_title_X360 = "TranslationHere",--Controller Disconnected
dialog_game_is_installing = "TranslationHere",--Cannot join invite at this time. Try again when the game has completed installing.
dialog_unlock_skill_switch_offshore = "TranslationHere",--It will cost you $offshore; offshore cash.
sm_hoxton_revenge_desc = "TranslationHere",--Hoxton used his time on the inside well. He wasn't even out of his prison pyjamas before busting in the FBI headquarters and getting everything he could about the rat. No name - the Feds are too canny for that - but the location of the safehouse where the rat is being held. Time to finish this.
dialog_assets_buy_title = "TranslationHere",--Are you sure?
dialog_skip_signin_warning_X360 = "TranslationHere",--Without signing in your progress will not be saved.$NL;$NL;Continue without saving?
dialog_yes = "TranslationHere",--Yes
dialog_mp_invite_wrong_room_message = "TranslationHere",--The game you have been invited to no longer exists. You are unable to join.
dialog_require_dlc_gage_pack_jobs = "TranslationHere",--Requires Gage Mod Courier DLC!
dialog_continue_cs_text = "TranslationHere",--Do you want to continue your Crime Spree?$NL;This will allow you to continue your Crime Spree from $level;$BTN_SPREE_TICKET; to gain Crime Spree Ranks and accumulate greater rewards.$NL;$NL;This will cost you $cost; Continental Coins.
dialog_joining_lobby_title = "TranslationHere",--Joining game
dialog_retrieving_servers_title = "TranslationHere",--Retrieving games
screen_autosaving_warning_X360 = "TranslationHere",--This game saves data automatically at certain points.$NL;Please don't turn off your Xbox One when the following icon is displayed:
dialog_connect_controller_text = "TranslationHere",--No Wireless Controller, Please Reconnect Controller
dialog_blackmarket_mod_replace = "TranslationHere",--This will replace your current modification $mod;.
dialog_default_options_message = "TranslationHere",--Do you wish to reset all options to their default state?
dialog_bm_mask_custom_abort = "TranslationHere",--Are you sure?
dialog_no_chat_parental_control = "TranslationHere",--CHAT IS DISABLED ON YOUR Sony Entertainment Network Account DUE TO PARENTAL CONTROL RESTRICTIONS.
dialog_blackmarket_mod_add = "TranslationHere",--You are about to add modification $mod; to your weapon.
dialog_save_settings_failed = "TranslationHere",--Saving operation failed
dialog_mp_disconnected_internet_PS3 = "TranslationHere",--You have been disconnected from "PlayStation Network". You must be connected to access the online portions of this title.
dialog_unlock_skill_switch_title = "TranslationHere",--Are you sure?
dialog_fail_load_setting_corrupt = "TranslationHere",--Settings file corrupt. Data will now be deleted.
dialog_accept_changes_title = "TranslationHere",--CONFIRM CHANGE?
dialog_cs_crash_fail = "TranslationHere",--Crime Spree Failed
dialog_fail_load_progress_corrupt_retry = "TranslationHere",--Progress could not be loaded. Try loading again?
dialog_err_not_signed_in = "TranslationHere",--YOU MUST BE ONLINE TO MAKE USE OF NETWORK MODES.
dialog_no_connection_to_game_servers = "TranslationHere",--Connection to game servers could not be established.
dialog_ask_load_progress_backup_wrong_version = "TranslationHere",--Progress profile wrong version. Load from Backup? Chosing NO will delete your progress.
dialog_connect_controller_title_WIN32 = "TranslationHere",--No controller
dialog_default_options_title = "TranslationHere",--Reset options
dialog_mp_restart_level_title = "TranslationHere",--Restart
dialog_bm_mask_sell_title = "TranslationHere",--Are you sure?
dialog_mp_restart_level_message = "TranslationHere",--Are you sure you want to create a vote for restarting?
dialog_safehouse_title = "TranslationHere",--Safe house
dialog_bm_weapon_modify_title = "TranslationHere",--Are you sure?
dialog_are_you_sure_you_want_to_clear_progress = "TranslationHere",--Are you sure you want to clear your progress? This will reset your cash, reputation level and your inventory.
dialog_mp_kick_player_title = "TranslationHere",--Kick player
dialog_mp_groupinvite_title = "TranslationHere",--Game Request
err_load = "TranslationHere",--Loading trophies...
dialog_item_list_macro = "TranslationHere",--$num;x $item;
dialog_fail_load_setting_wrong_version = "TranslationHere",--Settings file wrong version. Version $VERSION; or higher is required. Data will now be deleted.
dialog_blackmarket_abort_mask_warning = "TranslationHere",--Your mask has not been finalized. Aborting will leave the mask unchanged.
dialog_are_you_sure_you_want_to_quit = "TranslationHere",--Are you sure you want to quit?
dialog_gage_assignment_completed = "TranslationHere",--From: Gage [gage@///REDACTED///]$NL;To: $player;$NL;Date: $date; $time;$NL;Subject: GAGE COURIER ASSIGNMENTS$NL;$NL;GOOD JOB!$NL;$NL;Well done, $player;. Thanks for collecting the packages. It's time to get your reward. Go to your inventory and you will find the content of the following packages:$NL;$completed;$NL;$NL;- Gage
dialog_game_started = "TranslationHere",--The game is currently not joinable
dialog_infamous_info_desc = "TranslationHere",--You don't have what it takes yet. To become infamous, you will need to get to reputation level $level; and pay a fee of $cash; from your offshore account along with your skill points and the rest of your spending cash.
dialog_mp_kicked_out_message = "TranslationHere",--You've been kicked from the game.
dialog_can_become_infamous_desc = "TranslationHere",--You have fulfilled the conditions for the next level of infamy. To become infamous, press '$become_infamous_menu_item;' in the main menu.
dialog_challenge_warn_choose_reward = "TranslationHere",--Is this the reward you want?$NL;$reward;
dialog_infamytree_reseted = "TranslationHere",--Changes have been made to the infamy tree.$NL;$NL;All your infamy items have been reset and your infamy points have been refunded.
dialog_vote_cancel = "TranslationHere",--Abstain
dialog_load_wrong_user = "TranslationHere",--Save data belongs to a different user. No progress will be saved and trophies cannot be unlocked.
dialog_continue = "TranslationHere",--Continue
dialog_err_cant_join_from_game = "TranslationHere",--You must leave your current game before joining a new one.
dialog_repair_weapon_message = "TranslationHere",--Do you want to repair weapon "$WEAPON;" for $COST;?
ps4_presence_SPEnd = "TranslationHere",--Singleplayer heist ended
dialog_err_room_no_longer_exists = "TranslationHere",--This room no longer exists, please try another one.
dialog_authentication_fail = "TranslationHere",--Steam could not authenticate your Steam ID.
dialog_err_room_is_closed = "TranslationHere",--This room is closed, please try another one.
dialog_account_picker = "TranslationHere",--Switching profiles might cause unsaved progress to be lost. Do you wish to continue?
dialog_wait = "TranslationHere",--Please wait
dialog_err_failed_searching_lobbys = "TranslationHere",--Failed retrieving games.
dialog_blackmarket_num_in_inventory = "TranslationHere",--You own $amount; $item; already.
dialog_blackmarket_mod_remove = "TranslationHere",--You are about to remove modification $mod; from your weapon.
dialog_unlock_skill_switch_spending = "TranslationHere",--It will cost you $spending; spending cash.
dialog_new_unlock_primaries = "TranslationHere",--$value; has been unlocked and can be purchased into one of your empty primary weapon slots.
dialog_logging_in = "TranslationHere",--Logging in
dialog_bm_crafted_sell_title = "TranslationHere",--Are you sure?
err_ins = "TranslationHere",--An error occurred while loading trophies. Please exit the game and try again.
dialog_signin_change_X360 = "TranslationHere",--A sign-in change occurred.$NL;You have been returned to the Title screen.
dialog_err_room_allready_joined = "TranslationHere",--You have already joined this room.
dialog_fetching_status_title = "TranslationHere",--Updating online state.
dialog_mp_restart_level_host_message = "TranslationHere",--Are you sure you want to restart?
dialog_mp_disconnected_internet = "TranslationHere",--YOU HAVE BEEN DISCONNECTED
dialog_remove_dead_peer = "TranslationHere",--Connection to one or more players could not be established.
dialog_waiting_for_server_response_title = "TranslationHere",--Waiting for game to respond
dialog_blackmarket_assemble_item = "TranslationHere",--Do you really want to put together $item; mask and place it into your inventory?$NL;$NL;$num_in_inventory;
dialog_are_you_sure_you_want_to_reset_statistics = "TranslationHere",--Are you sure you want to reset your statistics?
dialog_skip_storage_warning_X360 = "TranslationHere",--No storage device selected.$NL;If you proceed without selecting a storage device, you will not be able to save the game.$NL;$NL;Continue without saving?
dialog_buy_weapon_title = "TranslationHere",--Buy
dialog_fail_load_setting_wrong_version_retry = "TranslationHere",--Settings file wrong version. Version $VERSION; or higher is required. Try loading again?
dialog_are_you_sure_you_want_to_leave_game = "TranslationHere",--Are you sure you want to leave current game?
dialog_mp_invite_join_message = "TranslationHere",--Please join this game using the 'View Invites' option in the Crime.net menu.
dialog_demo_info_text = "TranslationHere",--Thanks for installing our demo!$NL;$NL;In this demo of PAYDAY 2, you can level up with your character to level 10. Please note that your save file for the demo can not be brought over to the full game.$NL;$NL;We in the OVERKILL crew hope you enjoy this demo. If you like what you see, you can buy PAYDAY 2 where you may gain may more levels through our Infamy system. The full game also includes more content like more heists, weapons, weapon modifications, masks and more.$NL;$NL;- The OVERKILL crew
dialog_inactive_user_accepted_invite_error = "TranslationHere",--An invitation has been accepted by an inactive user. The invitation will be ignored.
dialog_blackmarket_slot_item_sell = "TranslationHere",--If you sell this, you will be paid $money;.
dialog_cs_cant_claim_rewards_text = "TranslationHere",--You have no rewards to claim.
dialog_err_room_is_full_X360 = "TranslationHere",--This game has been filled, please try another one.
dialog_err_room_no_longer_exists_X360 = "TranslationHere",--This game no longer exists, please try another one.
dialog_fail_load_game_corrupt = "TranslationHere",--Save file corrupt. Unable to load game.
dialog_infamous_info_title = "TranslationHere",--Infamy
dialog_infamy_reseted_title = "TranslationHere",--Please note
dialog_mission_asset_buy = "TranslationHere",--$asset_desc;$NL;$NL;Cost: $cost;.
dialog_mp_no_invites_message = "TranslationHere",--You have no game invites.
dialog_mp_vote_kick_unknown_message = "TranslationHere",--A vote has been initiated to kick someone currently connecting. The vote will end in $time; seconds.
dialog_npcommerce_fail_open = "TranslationHere",--FAILED INITIALIZING PlayStation®Store
dialog_npcommerce_opening = "TranslationHere",--INITIALIZING PlayStation®Store
dialog_repair_weapon_title = "TranslationHere",--Repair
dialog_request_timed_out_message = "TranslationHere",--Request to join game timed out
dialog_request_timed_out_title = "TranslationHere",--Timed out
dialog_signin_title_X360 = "TranslationHere",--Not signed in
dialog_unlock_skilltree = "TranslationHere",--You are about to start $skill; skill tree.$NL;$NL;It will cost $cost; and $points; out of $remaining_points; points.
dialog_use_default_keys_message = "TranslationHere",--Do you wish to reset all keys to their default state?
err_disk = "TranslationHere",--Not enough available space to load trophies. Please exit the game, ensure there is at least $MB;MB space available and try again.
ps4_presence_MPEnd = "TranslationHere",--Multiplayer heist ended
ps4_presence_MPLobby = "TranslationHere",--Multiplayer lobby
ps4_presence_MPPlaying = "TranslationHere",--Playing multiplayer heist
ps4_presence_SafeHousePlaying = "TranslationHere",--In the safe house
sm_2_desc = "TranslationHere",--Okay, so this might just work out. Preparation is important though. You're a professional. You need the right gear for the job. Okay, there may not be much in the cupboard right now, but as you keep pulling off heists, get notorious, we'll get those racks and cabinets filled with all the right gear.
sm_first_safehouse_desc = "TranslationHere",--Since you'll be out on the streets wreaking havoc, you're gonna need a place to call home- a safe house. I got just the place. It's nothing too fancy but it will have to do for now. Head over there and check it out, then later we can go about making some money.
