intro_hospital40 = "LOUP : Les mecs... on dirait qu'il y a quelque chose dans l'air... de l'argent!",--WOLF: Guys... it feels like something's in the air... money!
mission_suburbia_mission2_hack1 = "Remplacez le code de verrouillage de Mitchell.",--Override Mitchell's code lock.
mission_slaughterhouse_locate_van_hl = "Rendez-vous au camion blindé !",--Get to the armored truck!
intro_hospital95 = "Que diable - vous n'êtes pas médecins, n'est-ce pas ?",--What the hell - you ain't doctors, are ya?
mission_apartment_panic_hl = "Entrez dans la salle de panique (étage 3.)",--Get into the Panic Room (Floor 3.)
mission_suburbia_mission9_hl = "PRENEZ L'INTÉRIEUR DE L'ABRI.",--GET INSIDE THE SHELTER.
tip_head_shot = "Les coups à la tête sont plus efficaces que les coups à toute autre partie du corps.",--Shots to the head are more effective than shots to any other body part.
location_hospital_outsideICU = "À l'extérieur de l'unité de soins intensifs",--Outside ICU
location_vault = "Dans le coffre-fort.",--In Vault.
recoil_multiplier = "Cette mise à niveau réduira la quantité de recul de tir.$NL;Cela facilite l'obtention d'une série de tirs ciblés.",--This upgrade will lower the amount of firing recoil.$NL;This makes it easier to land a series of aimed shots.
mission_suburbia_mission3_sub_3 = "Charge désamorcée.",--Charge defused.
mission_empty_vault = "Vider le coffre-fort",--Empty the Vault (Vault)
mission_apartment_snipes_hl = "Sortez les tireurs d'élite",--Take out the snipers (Roof.)
location_suburbia_str3 = "Sur Marine Str.",--On Marine Str.
location_hospital_westCorridor = "Couloir ouest",--West Corridor
mission_suburbia_mission12 = "Laissez Bain vous dire comment entrer dans ce coffre-fort.",--Let Bain tell you how to enter this safe.
mission_suburbia_mission4_hl = "PERCER UN TROU ET RACCORDER LE TUYAU AU COFFRE-FORT.",--DRILL A HOLE AND CONNECT THE HOSE TO THE SAFE.
intro_hospital34 = "ÉTRANGER : Tenez la porte ! Tenir la porte!! LOUP : Bonjour, monsieur.",--STRANGER: Hold the door! Hold the door!! WOLF: Good day, sir.
mission_boat_saw = "Sciez l'obélisque pour briser la cage de verre.",--Saw down the obelisk to break the glass-cage.
location_suburbia_m_cellar = "Dans la cave de Mitchell",--In Mitchell's Cellar
enter_steelsight_speed_multiplier = "Cette mise à niveau réduit le temps nécessaire pour afficher les viseurs d'armes.$NL;Bon lorsque vous devez passer rapidement à la visée de précision.",--This upgrade decreases the time needed to bring up weapon sights.$NL;Good when you need to quickly switch to precision aiming.
location_hospital_Morgue = "Morgue",--Morgue
mission_boat_escape_hl = "Échapper",--Escape.
intro_hospital117 = "LOUP : Bain, grand-père parlait ici - donc on n'a rien entendu.",--WOLF: Bain, grampa over here was talking - so we didn't hear shit.
mission_suburbia_mission3_sub_1 = "Charge désamorcée.",--Charge defused.
location_dh_elevators22 = "Par Ascenseurs Étage 22.",--By Elevators Floor 22.
mission_undercover_escape2 = "Fuyez, un hélicoptère viendra vous chercher sur le toit voisin.",--Make the escape, a helicopter will pick you up on the neighbouring rooftop.
location_bridge_construction = "Au Chantier.",--At Construction.
intro_hospital142 = "LOUP: Oui oui oui. Cours le plan!",--WOLF: Yeah yeah yeah. Run the plan!
mission_hospital_escape = "Faire l'échapé",--Make the escape.
intro_hospital132 = "LOUP: Oui oui oui. Cours le plan!",--WOLF: Yeah yeah yeah. Run the plan!
mission_apartment_snipes = "Sortez tous les tireurs d'élite sur les toits autour du bâtiment afin que l'hélicoptère puisse déposer le C4.",--Take out all snipers on the rooftops around the building so that the helicopter can drop off the C4.
intro_apartment03 = "Cette salle de panique qu'ils ont là-dedans va être pleine d'argent...",--That panic room they got in there is gonna be full of cash...
location_server = "Dans la salle des serveurs.",--In Server Room.
des_more_blood_to_bleed = "Le temps de saignement de tous vos coéquipiers augmente. Le bénéfice d'un Crew Bonus ne s'applique qu'aux trois coéquipiers de celui qui l'équipe. Cela signifie qu'un autre membre de l'équipe doit équiper un bonus d'équipage pour que vous puissiez en bénéficier directement. Les multiplicateurs ne se cumulent pas si plusieurs coéquipiers équipent le même bonus d'équipage.",--All your teammates bleedout time increases. The benefit of a Crew Bonus only applies to the three teammates of the one who equips it. This means that someone else on the team needs to equip a crew bonus in order for you to directly benefit from it. Multipliers do not stack if several teammates equip the same crew bonus.
intro_hospital48 = "LOUP : Bain, je n'ai pas entendu de squat parce que le vieux McDonald ici parlait tout le temps...",--WOLF: Bain, I didn't hear squat cause Old McDonald over here was talking all the time...
tip_xp = "Vous obtenez de l'argent en complétant des objectifs, des défis et en volant du butin. $NL; $NL; La collecte de récompenses en espèces augmente votre réputation, ce qui vous donne à son tour accès à de nouvelles armes, équipements et capacités.",--You get cash by completing objectives, challenges and stealing loot. $NL; $NL; Collecting cash rewards increases your reputation, which in turn gives you access new weapons, equipment and abilities.
intro_hospital71 = "BAIN: Vous rompez - vous m'entendez bien?",--BAIN: You're breaking up - can you hear me OK?
tip_law_enforcers_as_hostages = "S'il n'y a pas de civils à prendre en otages, vous pouvez toujours prendre en otage des forces de l'ordre.",--If there are no civilians to take as hostages, you can always take law enforcers as hostages.
mission_diamond_wait_hl = "Attendez Bain.",--Wait for Bain.
mission_boat_restart_engine_hl = "Redémarrez le moteur.",--Restart the engine.
extra_ammo_multiplier = "Cette mise à niveau augmente la quantité maximale de munitions.$NL;Si vous êtes satisfait de la gâchette, alors ça pourrait être ça.",--This upgrade increases the maximum amount of ammo.$NL;If you are trigger happy, then This could be it.
intro_hospital120 = "LOUP : Les mecs... on dirait qu'il y a quelque chose dans l'air... de l'argent!",--WOLF: Guys... it feels like something's in the air... money!
location_str_2ave = "Sur l'avenue Major.",--On Major Ave.
intro_street04_2 = "Hah, je vous ai trompé les gars!",--Hah, fooled ya guys!
intro_hospital82 = "LOUP: Oui oui oui. Cours le plan!",--WOLF: Yeah yeah yeah. Run the plan!
