debug_interact_glass_cutter = "Maintenez $BTN_INTERACT; pour placer le cutter",--Hold $BTN_INTERACT; to Place the Cutter
debug_equipment_crowbar = "PIED-DE-BICHE",--CROWBAR
debug_interact_hack_ipad_PS3 = "Maintenez $BTN_INTERACT; pour configurer l'appareil",--Hold $BTN_INTERACT; to set up Device
debug_interact_diamond_case_PS3 = "Appuyez sur $BTN_INTERACT; ouvrir",--Press $BTN_INTERACT; to open
debug_interact_sentry_gun_reload = "Maintenez $BTN_INTERACT; pour recharger Sentry Gun$NL;( Munitions restantes: $AMMO; )",--Hold $BTN_INTERACT; to reload Sentry Gun$NL;( Ammo Remaining: $AMMO; )
debug_interact_equipment_drill = "Utilisez la perceuse pour accéder au coffre-fort",--Use the Drill to get to the Vault
debug_interact_gold_bag_PS3 = "Maintenez $BTN_INTERACT; ramasser le sac",--Hold $BTN_INTERACT; to Pick up the Bag
debug_interact_hack_ipad_jammed = "Maintenez $BTN_INTERACT; redémarrer",--Hold $BTN_INTERACT; to reboot
debug_interact_hostage_move = "Maintenez $BTN_INTERACT; déplacer l'otage",--Hold $BTN_INTERACT; to move the hostage
debug_interact_money_bag_PS3 = "Appuyez sur $BTN_INTERACT; placer le sac d'argent",--Press $BTN_INTERACT; to Place the Money Bag
debug_wskn_want_to_save = "Voulez-vous enregistrer vos modifications?",--Do you want to save your changes?
debug_interact_ammo_bag_take_ammo = "Maintenez $BTN_INTERACT; prendre des munitions",--Hold $BTN_INTERACT; to Take Ammo
debug_equipment_bodybags_bag = "Sac mortuaire",--Body Bag Case
debug_wskn_screenshot_skin = "Capture d'écran",--Screenshot
debug_wskn_uv_scale_x = "Largeur de l'autocollant",--Sticker Width
debug_debug_font_draw_text = "@ £ $ () % ^ } ´ W$BTN_INV_NEW;W$BTN_GHOST;W$BTN_SKULL;W $NL;_le $BTN_BACK;rapide $BTN_START;marron $BTN_A;renard $BTN_TOP_L;saute $BTN_BOTTOM_L;sur $BTN_STICK_L;le $BTN_INTERACT;paresseux $BTN_RELOAD;chien $BTN_GADGET; j g y",--@ £ $ () % ^  } ´ W$BTN_INV_NEW;W$BTN_GHOST;W$BTN_SKULL;W $NL;_the $BTN_BACK;quick $BTN_START;brown $BTN_A;fox $BTN_TOP_L;jumps $BTN_BOTTOM_L;over $BTN_STICK_L;the $BTN_INTERACT;lazy $BTN_RELOAD;dog $BTN_GADGET; j g y
debug_interact_gold_bag = "Maintenez $BTN_INTERACT; ramasser le sac",--Hold $BTN_INTERACT; to Pick up the Bag
debug_wskn_wear_and_tear = "Qualité de l'aperçu",--Preview Quality
debug_interact_drill_PS3 = "Maintenez $BTN_INTERACT; placer la perceuse",--Hold $BTN_INTERACT; to Place the Drill
debug_button_a = "$BTN_A;",--$BTN_A;
debug_instruct_finish_arrest_PS3 = "Appuyez sur $BTN_INTERACT; se lever",--Press $BTN_INTERACT; to get up
debug_interact_c4_bag_PS3 = "Maintenez $BTN_INTERACT; ramasser des explosifs",--Hold $BTN_INTERACT; to Pick up Explosives
debug_interact_saw_jammed = "Maintenez $BTN_INTERACT; pour redémarrer la scie",--Hold $BTN_INTERACT; to Restart the Saw
debug_god_mode = "Mode Dieu",--God Mode
debug_heist_successful = "Réussissement du braquage!",--HEIST SUCCESSFUL!
debug_interact_security_station = "Appuyez $BTN_INTERACT; pour démarrer la surcharge",--Hold $BTN_INTERACT; to Start the Override
debug_interact_doctor_bag_heal = "Maintenez $BTN_INTERACT; pour vous rafistoler",--Hold $BTN_INTERACT; to Patch Yourself Up
debug_lu_upgrade_awarded = "Amélioration gagnée",--UPGRADE AWARDED
debug_wskn_uv_offset_rot_y = "Autocollant Y",--Sticker Y
debug_equipment_armor_kit = "Sac d'armure",--Armor Bag
debug_interact_open_door_PS3 = "Appuyez $BTN_INTERACT; pour ouvrir la  porte",--Press $BTN_INTERACT; to Open The Door
debug_interact_patient_paper = "Maintenez $BTN_INTERACT; pour regarder les fichiers",--Hold $BTN_INTERACT; TO CHECK FILE
debug_interact_thermite = "Maintenez $BTN_INTERACT; pour placer les thermites",--Hold $BTN_INTERACT; to place the Thermite
debug_lu_reached_level = "ATTEIND$NL;NIVEAU DE RÉPUTATION",--REACHED$NL;REPUTATION LEVEL
debug_upgrade_player_upgrade = "AMÉLIORATION DE JOUEUR",--PLAYER UPGRADE
debug_wskn_black = "Noir",--Black
debug_wskn_none = "Rien",--None
debug_m79 = "Lance grenade GL40",--GL40 grenade launcher
debug_glock = "Pistolet Strike",--Stryk pistol
debug_interact_equipment_glass_cutter = "Utilisez le coupeur pour couper à travers les vitre",--Use the Cutter to cut through the glass
debug_team_mate_need_revive = "Allié est bas!",--Teammate is Down!
debug_interact_apartment_key_PS3 = "Appuyez $BTN_INTERACT; pour utiliser la clef",--Press $BTN_INTERACT; to use the Key
debug_equipment_drill = "Perceuse",--Drill
debug_interact_money_bag = "Appuyez sur $BTN_INTERACT; placer le sac d'argent",--Press $BTN_INTERACT; to Place the Money Bag
debug_interact_doctor_bag_heal_PS3 = "Maintenez $BTN_INTERACT; pour vous rafistoler",--Hold $BTN_INTERACT; to Patch Yourself Up
debug_trade_hostage = "Échange d'otage pour votre allié",--Trade hostage for your teammate!
debug_interact_bodybags_bag_take_bodybag = "Maintenez $BTN_INTERACT; attraper un sac organique",--Hold $BTN_INTERACT; to grab a body bag
debug_interact_grenade_crate_take_grenades = "Maintenez $BTN_INTERACT; attraper un jetable",--Hold $BTN_INTERACT; to grab a throwable
debug_interact_hold_to_breach = "Maintenez $BTN_INTERACT; transgresser",--Hold $BTN_INTERACT; to Breach
debug_interact_hospital_sentry = "maintenez $BTN_INTERACT; installer la mitrailleuse",--hold $BTN_INTERACT; to set up the sentry gun
debug_interact_hospital_phone = "Appuyez sur $BTN_INTERACT; répondre au téléphone",--Press $BTN_INTERACT; to answer the phone
debug_wskn_customize = "Peau de débogage",--Debug Skin
debug_upgrade_tree_support = "les secours",--SUPPORT
debug_interact_equipment_gold = "Vous avez besoin d'or!",--You need Gold!
debug_interact_free_PS3 = "Maintenez $BTN_INTERACT; pour sauver votre coéquipier",--Hold $BTN_INTERACT; to Rescue your Teammate
debug_interact_apartment_helicopter = "Maintenez $BTN_INTERACT; pour attacher le champ magnétique",--Hold $BTN_INTERACT; to Attach the Magnet
debug_give_alot_of_lootdrops = "Donnez beaucoup de butins (1000 de chaque classe de paiement)",--Give alot of lootdrops (1000 of each payclass)
debug_give_alot_of_money = "Donner de l'argent (10 travaux terminés de chaque étoile)",--Give money (10 completed jobs of each star)
debug_instruct_finish_arrest = "Appuyez sur $BTN_INTERACT; se lever",--Press $BTN_INTERACT; to get up
debug_interact_cutter_jammed_PS3 = "Maintenez $BTN_INTERACT; pour redémarrer le coupeur",--Hold $BTN_INTERACT; to Restart the Cutter
debug_suburbia = "falsifier",--Counterfeit
debug_upgrade_new_equipment = "NOUVEL ÉQUIPEMENT",--NEW EQUIPMENT
debug_interact_laptop_objective_PS3 = "Maintenez $BTN_INTERACT; Effacer les images de sécurité",--Hold $BTN_INTERACT; to Erase security footage
debug_wskn_submit_no_screenshot = "Aucune capture d'écran sélectionnée",--No screenshot selected
debug_interact_equipment_requires_cable_ties = "Vous avez besoin de serre-cravattes",--You need cable ties
debug_modify_active_challenges = "Modifier les défis actifs",--Modify active challenges
debug_interact_trip_mine_PS3 = "Appuyez sur $BTN_INTERACT; pour activer ou désactiver trébucher le mien",--Press $BTN_INTERACT; to Turn Trip Mine On or Off
debug_wskn_sure_to_delete = "Voulez-vous vraiment supprimer ce thème?",--Are you sure you want to delete this skin?
debug_interact_equipment_gas = "Vous avez besoin d'essence",--You need Gasoline
debug_interact_c4_PS3 = "Maintenez $BTN_INTERACT; placer les explosifs",--Hold $BTN_INTERACT; to Place the Explosives
debug_wskn_cubemap_pattern_control_x = "Motif intensité de la carte cubique",--Pattern Cubemap Intensity
